*
* file generated by qgraf-3.5.0
*

Local loop2diagram1=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,-k1+k2,0)*
 glprop(11,12,k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,9,-k1+k2,7,-k2)*
 vrtx(Uug,8,k2,11,k1-k2-p4,5,-k1+p4)*
 vrtx(gggg,-6,-p3,2,-p1-p2,10,k1-k2,12,-k1+k2+p4)
;
Local loop2diagram2=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2-p4+p1,0)*
 glprop(11,12,-k1-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,2,p4-p1,9,k2-p4+p1,7,-k2)*
 vrtx(Uug,8,k2,11,-k1-k2,3,k1)*
 vrtx(gggg,-6,-p3,6,-k1-p2,10,-k2+p4-p1,12,k1+k2)
;
Local loop2diagram3=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2-p4+p2,0)*
 glprop(11,12,-k1-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,8,-k2,9,k2-p4+p2,1,p4-p2)*
 vrtx(Uug,4,k1,11,-k1-k2,7,k2)*
 vrtx(gggg,-6,-p3,6,-k1-p1,10,-k2+p4-p2,12,k1+k2)
;
Local loop2diagram4=

 +(1/2)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 glprop(7,8,-k1-p4+p1,0)*
 glprop(9,10,-k1+k2-p4+p1,0)*
 glprop(11,12,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,2,p4-p1,7,-k1-p4+p1,3,k1)*
 vrtx(ggg,8,k1+p4-p1,9,-k1+k2-p4+p1,11,-k2)*
 vrtx(gggg,-6,-p3,6,-k1-p2,10,k1-k2+p4-p1,12,k2)
;
Local loop2diagram5=

 +(1/2)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 glprop(7,8,-k1-p4+p2,0)*
 glprop(9,10,-k1+k2-p4+p2,0)*
 glprop(11,12,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,4,k1,7,-k1-p4+p2,1,p4-p2)*
 vrtx(ggg,8,k1+p4-p2,9,-k1+k2-p4+p2,11,-k2)*
 vrtx(gggg,-6,-p3,6,-k1-p1,10,k1-k2+p4-p2,12,k2)
;
Local loop2diagram6=

 +(1/2)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 glprop(7,8,-k1-p4+p1,0)*
 glprop(9,10,k1+k2+p2,0)*
 glprop(11,12,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,2,p4-p1,7,-k1-p4+p1,3,k1)*
 vrtx(ggg,6,-k1-p2,9,k1+k2+p2,11,-k2)*
 vrtx(gggg,-6,-p3,8,k1+p4-p1,10,-k1-k2-p2,12,k2)
;
Local loop2diagram7=

 +(1/2)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 glprop(7,8,-k1-p4+p2,0)*
 glprop(9,10,k1+k2+p1,0)*
 glprop(11,12,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,4,k1,7,-k1-p4+p2,1,p4-p2)*
 vrtx(ggg,6,-k1-p1,9,k1+k2+p1,11,-k2)*
 vrtx(gggg,-6,-p3,8,k1+p4-p2,10,-k1-k2-p1,12,k2)
;
Local loop2diagram8=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 glprop(11,12,k1-k2-p4,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,4,-k1+p4,11,k1-k2-p4,7,k2)*
 vrtx(gggg,-6,-p3,6,k1-p1,10,-k2-p2,12,-k1+k2+p4)
;
Local loop2diagram9=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,k1-k2-p4,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,8,k2,11,k1-k2-p4,3,-k1+p4)*
 vrtx(gggg,-6,-p3,6,k1-p2,10,-k2-p1,12,-k1+k2+p4)
;
Local loop2diagram10=

 +(1/2)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+k2+p1,0)*
 glprop(11,12,-k2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(ggg,6,k1-p1,9,-k1+k2+p1,11,-k2)*
 vrtx(gggg,-6,-p3,8,-k1+p4-p2,10,k1-k2-p1,12,k2)
;
Local loop2diagram11=

 +(1/2)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+k2+p2,0)*
 glprop(11,12,-k2,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,7,k1-p4+p1,3,-k1+p4)*
 vrtx(ggg,6,k1-p2,9,-k1+k2+p2,11,-k2)*
 vrtx(gggg,-6,-p3,8,-k1+p4-p1,10,k1-k2-p2,12,k2)
;
Local loop2diagram12=

 +(1/2)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 glprop(7,8,k2+p3,0)*
 glprop(9,10,-k2,0)*
 glprop(11,12,-k1-p4+p1,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,7,k2+p3,9,-k2)*
 vrtx(Uug,2,p4-p1,11,-k1-p4+p1,3,k1)*
 vrtx(gggg,6,-k1-p2,12,k1+p4-p1,8,-k2-p3,10,k2)
;
Local loop2diagram13=

 +(1/2)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 glprop(7,8,k2+p3,0)*
 glprop(9,10,-k2,0)*
 glprop(11,12,-k1-p4+p2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(ggg,-6,-p3,7,k2+p3,9,-k2)*
 vrtx(Uug,4,k1,11,-k1-p4+p2,1,p4-p2)*
 vrtx(gggg,6,-k1-p1,12,k1+p4-p2,8,-k2-p3,10,k2)
;
Local loop2diagram14=

 +(1/2)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,k2+p3,0)*
 glprop(11,12,-k2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,9,k2+p3,11,-k2)*
 vrtx(gggg,6,k1-p1,8,-k1+p4-p2,10,-k2-p3,12,k2)
;
Local loop2diagram15=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-p2-p3,mt)*
 fpropu(5,6,-k1,mt)*
 glprop(7,8,k1-p4+p1,0)*
 fpropu(9,10,k2,mt)*
 glprop(11,12,k2+p2+p3,0)*
 glprop(13,14,-k1-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,2,p4-p1,7,k1-p4+p1,5,-k1)*
 vrtx(Uug,10,-k2,11,k2+p2+p3,3,-p2-p3)*
 vrtx(Uug,6,k1,13,-k1-k2,9,k2)*
 vrtx(ggg,8,-k1+p4-p1,12,-k2-p2-p3,14,k1+k2)
;
Local loop2diagram16=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-p2-p3,mt)*
 fpropu(5,6,-k1,mt)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,-k2-p2-p3,mt)*
 fpropu(13,14,-k1-k2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,2,p4-p1,7,k1-p4+p1,5,-k1)*
 vrtx(Uug,12,k2+p2+p3,9,-k2,3,-p2-p3)*
 vrtx(Uug,6,k1,10,k2,13,-k1-k2)*
 vrtx(Uug,14,k1+k2,8,-k1+p4-p1,11,-k2-p2-p3)
;
Local loop2diagram17=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,p1+p3,mt)*
 fpropu(5,6,k1,mt)*
 glprop(7,8,k1-p4+p2,0)*
 fpropu(9,10,-k2,mt)*
 glprop(11,12,k2+p1+p3,0)*
 glprop(13,14,-k1-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,-6,-p3,3,p1+p3)*
 vrtx(Uug,6,-k1,7,k1-p4+p2,1,p4-p2)*
 vrtx(Uug,4,-p1-p3,11,k2+p1+p3,9,-k2)*
 vrtx(Uug,10,k2,13,-k1-k2,5,k1)*
 vrtx(ggg,8,-k1+p4-p2,12,-k2-p1-p3,14,k1+k2)
;
Local loop2diagram18=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,p1+p3,mt)*
 fpropu(5,6,k1,mt)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,k2+p1+p3,mt)*
 fpropu(13,14,k1+k2,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,-6,-p3,3,p1+p3)*
 vrtx(Uug,6,-k1,7,k1-p4+p2,1,p4-p2)*
 vrtx(Uug,4,-p1-p3,9,-k2,11,k2+p1+p3)*
 vrtx(Uug,14,-k1-k2,10,k2,5,k1)*
 vrtx(Uug,12,-k2-p1-p3,8,-k1+p4-p2,13,k1+k2)
;
Local loop2diagram19=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-p2-p3,mt)*
 fpropu(5,6,k1-p4+p1,mt)*
 glprop(7,8,-k1,0)*
 fpropu(9,10,-k2-p2-p3,mt)*
 glprop(11,12,-k2,0)*
 fpropu(13,14,-p4+p1,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,2,p4-p1,7,-k1,5,k1-p4+p1)*
 vrtx(Uug,10,k2+p2+p3,11,-k2,3,-p2-p3)*
 vrtx(Uug,6,-k1+p4-p1,8,k1,13,-p4+p1)*
 vrtx(Uug,14,p4-p1,12,k2,9,-k2-p2-p3)
;
Local loop2diagram20=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,p1+p3,mt)*
 fpropu(5,6,-k1+p4-p2,mt)*
 glprop(7,8,-k1,0)*
 fpropu(9,10,k2+p1+p3,mt)*
 glprop(11,12,-k2,0)*
 fpropu(13,14,p4-p2,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,-6,-p3,3,p1+p3)*
 vrtx(Uug,6,k1-p4+p2,7,-k1,1,p4-p2)*
 vrtx(Uug,4,-p1-p3,11,-k2,9,k2+p1+p3)*
 vrtx(Uug,14,-p4+p2,8,k1,5,-k1+p4-p2)*
 vrtx(Uug,10,-k2-p1-p3,12,k2,13,p4-p2)
;
Local loop2diagram21=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-p2-p3,mt)*
 fpropu(5,6,-k1,mt)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 fpropu(11,12,k1+k2-p4+p1,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,2,p4-p1,7,k1-p4+p1,5,-k1)*
 vrtx(Uug,6,k1,9,-k1+p2+p3,3,-p2-p3)*
 vrtx(Uug,14,-k2,8,-k1+p4-p1,11,k1+k2-p4+p1)*
 vrtx(Uug,12,-k1-k2+p4-p1,10,k1-p2-p3,13,k2)
;
Local loop2diagram22=

 +(1/2)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-p2-p3,mt)*
 fpropu(5,6,-k1,mt)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 glprop(11,12,k1+k2-p4+p1,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,2,p4-p1,7,k1-p4+p1,5,-k1)*
 vrtx(Uug,6,k1,9,-k1+p2+p3,3,-p2-p3)*
 vrtx(ggg,8,-k1+p4-p1,11,k1+k2-p4+p1,13,-k2)*
 vrtx(ggg,10,k1-p2-p3,12,-k1-k2+p4-p1,14,k2)
;
Local loop2diagram23=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-p2-p3,mt)*
 fpropu(5,6,-k1,mt)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 ghprop(11,12,k1+k2-p4+p1,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,2,p4-p1,7,k1-p4+p1,5,-k1)*
 vrtx(Uug,6,k1,9,-k1+p2+p3,3,-p2-p3)*
 vrtx(Ghghg,14,-k2,8,-k1+p4-p1,11,k1+k2-p4+p1)*
 vrtx(Ghghg,12,-k1-k2+p4-p1,10,k1-p2-p3,13,k2)
;
Local loop2diagram24=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-p2-p3,mt)*
 glprop(5,6,-k1,0)*
 fpropu(7,8,k1-p4+p1,mt)*
 fpropu(9,10,k1-p2-p3,mt)*
 fpropu(11,12,k1+k2-p4+p1,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,2,p4-p1,5,-k1,7,k1-p4+p1)*
 vrtx(Uug,10,-k1+p2+p3,6,k1,3,-p2-p3)*
 vrtx(Uug,8,-k1+p4-p1,13,-k2,11,k1+k2-p4+p1)*
 vrtx(Uug,12,-k1-k2+p4-p1,14,k2,9,k1-p2-p3)
;
Local loop2diagram25=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,p1+p3,mt)*
 fpropu(5,6,k1,mt)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 fpropu(11,12,k1+k2-p4+p2,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,-6,-p3,3,p1+p3)*
 vrtx(Uug,6,-k1,7,k1-p4+p2,1,p4-p2)*
 vrtx(Uug,4,-p1-p3,9,-k1+p1+p3,5,k1)*
 vrtx(Uug,14,-k2,8,-k1+p4-p2,11,k1+k2-p4+p2)*
 vrtx(Uug,12,-k1-k2+p4-p2,10,k1-p1-p3,13,k2)
;
Local loop2diagram26=

 +(1/2)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,p1+p3,mt)*
 fpropu(5,6,k1,mt)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 glprop(11,12,k1+k2-p4+p2,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,-6,-p3,3,p1+p3)*
 vrtx(Uug,6,-k1,7,k1-p4+p2,1,p4-p2)*
 vrtx(Uug,4,-p1-p3,9,-k1+p1+p3,5,k1)*
 vrtx(ggg,8,-k1+p4-p2,11,k1+k2-p4+p2,13,-k2)*
 vrtx(ggg,10,k1-p1-p3,12,-k1-k2+p4-p2,14,k2)
;
Local loop2diagram27=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,p1+p3,mt)*
 fpropu(5,6,k1,mt)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 ghprop(11,12,k1+k2-p4+p2,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,-6,-p3,3,p1+p3)*
 vrtx(Uug,6,-k1,7,k1-p4+p2,1,p4-p2)*
 vrtx(Uug,4,-p1-p3,9,-k1+p1+p3,5,k1)*
 vrtx(Ghghg,14,-k2,8,-k1+p4-p2,11,k1+k2-p4+p2)*
 vrtx(Ghghg,12,-k1-k2+p4-p2,10,k1-p1-p3,13,k2)
;
Local loop2diagram28=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,p1+p3,mt)*
 glprop(5,6,-k1,0)*
 fpropu(7,8,-k1+p4-p2,mt)*
 fpropu(9,10,-k1+p1+p3,mt)*
 fpropu(11,12,-k1-k2+p4-p2,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,-6,-p3,3,p1+p3)*
 vrtx(Uug,8,k1-p4+p2,5,-k1,1,p4-p2)*
 vrtx(Uug,4,-p1-p3,6,k1,9,-k1+p1+p3)*
 vrtx(Uug,12,k1+k2-p4+p2,13,-k2,7,-k1+p4-p2)*
 vrtx(Uug,10,k1-p1-p3,14,k2,11,-k1-k2+p4-p2)
;
Local loop2diagram29=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2-p3,mt)*
 glprop(11,12,k1+k2,0)*
 fpropu(13,14,-k1-k2-p4+p1,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,10,k2+p3,-6,-p3,7,-k2)*
 vrtx(Uug,2,p4-p1,11,k1+k2,13,-k1-k2-p4+p1)*
 vrtx(Uug,8,k2,12,-k1-k2,3,k1)*
 vrtx(Uug,14,k1+k2+p4-p1,6,-k1-p2,9,-k2-p3)
;
Local loop2diagram30=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,k1+k2,mt)*
 glprop(13,14,-k1-k2-p4+p1,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,2,p4-p1,13,-k1-k2-p4+p1,11,k1+k2)*
 vrtx(Uug,12,-k1-k2,8,k2,3,k1)*
 vrtx(ggg,6,-k1-p2,10,-k2-p3,14,k1+k2+p4-p1)
;
Local loop2diagram31=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2+p3,mt)*
 glprop(11,12,k1+k2,0)*
 fpropu(13,14,k1+k2+p4-p2,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(Uug,14,-k1-k2-p4+p2,11,k1+k2,1,p4-p2)*
 vrtx(Uug,4,k1,12,-k1-k2,7,k2)*
 vrtx(Uug,10,-k2-p3,6,-k1-p1,13,k1+k2+p4-p2)
;
Local loop2diagram32=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,-k1-k2,mt)*
 glprop(13,14,-k1-k2-p4+p2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,12,k1+k2,13,-k1-k2-p4+p2,1,p4-p2)*
 vrtx(Uug,4,k1,8,k2,11,-k1-k2)*
 vrtx(ggg,6,-k1-p1,10,-k2-p3,14,k1+k2+p4-p2)
;
Local loop2diagram33=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2+p3,mt)*
 glprop(11,12,k1+k2,0)*
 glprop(13,14,-k1-k2+p1+p2,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(ggg,2,-p1-p2,11,k1+k2,13,-k1-k2+p1+p2)*
 vrtx(Uug,4,k1,12,-k1-k2,7,k2)*
 vrtx(Uug,10,-k2-p3,14,k1+k2-p1-p2,5,-k1+p4)
;
Local loop2diagram34=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,-k1-k2,mt)*
 fpropu(13,14,-k1-k2+p1+p2,mt)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,12,k1+k2,2,-p1-p2,13,-k1-k2+p1+p2)*
 vrtx(Uug,4,k1,8,k2,11,-k1-k2)*
 vrtx(Uug,14,k1+k2-p1-p2,10,-k2-p3,5,-k1+p4)
;
Local loop2diagram35=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 glprop(11,12,k1+k2,0)*
 fpropu(13,14,-k1-k2+p1+p3,mt)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,11,k1+k2,13,-k1-k2+p1+p3)*
 vrtx(Uug,4,k1,12,-k1-k2,7,k2)*
 vrtx(Uug,14,k1+k2-p1-p3,10,-k2-p2,5,-k1+p4)
;
Local loop2diagram36=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 fpropu(11,12,-k1-k2,mt)*
 glprop(13,14,-k1-k2+p2+p3,0)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,12,k1+k2,13,-k1-k2+p2+p3,1,-p2-p3)*
 vrtx(Uug,4,k1,8,k2,11,-k1-k2)*
 vrtx(Uug,10,-k2-p1,14,k1+k2-p2-p3,5,-k1+p4)
;
Local loop2diagram37=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2-p3,mt)*
 glprop(11,12,-k1-p4+p1,0)*
 fpropu(13,14,k1-k2+p2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,10,k2+p3,-6,-p3,7,-k2)*
 vrtx(Uug,2,p4-p1,11,-k1-p4+p1,3,k1)*
 vrtx(Uug,8,k2,6,-k1-p2,13,k1-k2+p2)*
 vrtx(Uug,14,-k1+k2-p2,12,k1+p4-p1,9,-k2-p3)
;
Local loop2diagram38=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2+p3,mt)*
 glprop(11,12,-k1-p4+p1,0)*
 fpropu(13,14,-k1+k2-p2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(Uug,2,p4-p1,11,-k1-p4+p1,3,k1)*
 vrtx(Uug,14,k1-k2+p2,6,-k1-p2,7,k2)*
 vrtx(Uug,10,-k2-p3,12,k1+p4-p1,13,-k1+k2-p2)
;
Local loop2diagram39=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 glprop(11,12,-k1-p4+p1,0)*
 glprop(13,14,k1-k2+p2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,2,p4-p1,11,-k1-p4+p1,3,k1)*
 vrtx(ggg,6,-k1-p2,8,k2,13,k1-k2+p2)*
 vrtx(ggg,12,k1+p4-p1,10,-k2-p3,14,-k1+k2-p2)
;
Local loop2diagram40=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 ghprop(7,8,-k2,0)*
 ghprop(9,10,-k2-p3,0)*
 glprop(11,12,-k1-p4+p1,0)*
 ghprop(13,14,k1-k2+p2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Ghghg,10,k2+p3,-6,-p3,7,-k2)*
 vrtx(Uug,2,p4-p1,11,-k1-p4+p1,3,k1)*
 vrtx(Ghghg,8,k2,6,-k1-p2,13,k1-k2+p2)*
 vrtx(Ghghg,14,-k1+k2-p2,12,k1+p4-p1,9,-k2-p3)
;
Local loop2diagram41=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 ghprop(7,8,k2,0)*
 ghprop(9,10,k2+p3,0)*
 glprop(11,12,-k1-p4+p1,0)*
 ghprop(13,14,-k1+k2-p2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Ghghg,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(Uug,2,p4-p1,11,-k1-p4+p1,3,k1)*
 vrtx(Ghghg,14,k1-k2+p2,6,-k1-p2,7,k2)*
 vrtx(Ghghg,10,-k2-p3,12,k1+p4-p1,13,-k1+k2-p2)
;
Local loop2diagram42=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2-p3,mt)*
 fpropu(11,12,-k1-p4+p1,mt)*
 glprop(13,14,k1-k2+p2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(Uug,10,k2+p3,-6,-p3,7,-k2)*
 vrtx(Uug,2,p4-p1,4,k1,11,-k1-p4+p1)*
 vrtx(Uug,8,k2,13,k1-k2+p2,5,-k1-p2)*
 vrtx(Uug,12,k1+p4-p1,14,-k1+k2-p2,9,-k2-p3)
;
Local loop2diagram43=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,-k1-p4+p1,mt)*
 fpropu(13,14,-k1+k2-p2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,2,p4-p1,4,k1,11,-k1-p4+p1)*
 vrtx(Uug,14,k1-k2+p2,8,k2,5,-k1-p2)*
 vrtx(Uug,12,k1+p4-p1,10,-k2-p3,13,-k1+k2-p2)
;
Local loop2diagram44=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1+p3,mt)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 glprop(11,12,-k1-p4+p1,0)*
 glprop(13,14,k1-k2+p3,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,-6,-p3,5,k1+p3)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,2,p4-p1,11,-k1-p4+p1,3,k1)*
 vrtx(Uug,6,-k1-p3,13,k1-k2+p3,7,k2)*
 vrtx(ggg,12,k1+p4-p1,10,-k2-p2,14,-k1+k2-p3)
;
Local loop2diagram45=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1+p3,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,-k2-p2,mt)*
 glprop(11,12,-k1-p4+p1,0)*
 fpropu(13,14,k1-k2+p3,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,-6,-p3,5,k1+p3)*
 vrtx(Uug,10,k2+p2,7,-k2,-4,-p2)*
 vrtx(Uug,2,p4-p1,11,-k1-p4+p1,3,k1)*
 vrtx(Uug,6,-k1-p3,8,k2,13,k1-k2+p3)*
 vrtx(Uug,14,-k1+k2-p3,12,k1+p4-p1,9,-k2-p2)
;
Local loop2diagram46=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 glprop(5,6,k1+p3,0)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 fpropu(11,12,-k1-p4+p1,mt)*
 fpropu(13,14,-k1+k2-p3,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(ggg,-6,-p3,3,-k1,5,k1+p3)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,2,p4-p1,4,k1,11,-k1-p4+p1)*
 vrtx(Uug,14,k1-k2+p3,6,-k1-p3,7,k2)*
 vrtx(Uug,12,k1+p4-p1,10,-k2-p2,13,-k1+k2-p3)
;
Local loop2diagram47=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 glprop(5,6,k1+p3,0)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,-k2-p2,mt)*
 fpropu(11,12,-k1-p4+p1,mt)*
 glprop(13,14,k1-k2+p3,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(ggg,-6,-p3,3,-k1,5,k1+p3)*
 vrtx(Uug,10,k2+p2,7,-k2,-4,-p2)*
 vrtx(Uug,2,p4-p1,4,k1,11,-k1-p4+p1)*
 vrtx(ggg,6,-k1-p3,8,k2,13,k1-k2+p3)*
 vrtx(Uug,12,k1+p4-p1,14,-k1+k2-p3,9,-k2-p2)
;
Local loop2diagram48=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2-p3,mt)*
 glprop(11,12,-k1-p4+p2,0)*
 fpropu(13,14,k1-k2+p1,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,10,k2+p3,-6,-p3,7,-k2)*
 vrtx(Uug,4,k1,11,-k1-p4+p2,1,p4-p2)*
 vrtx(Uug,8,k2,6,-k1-p1,13,k1-k2+p1)*
 vrtx(Uug,14,-k1+k2-p1,12,k1+p4-p2,9,-k2-p3)
;
Local loop2diagram49=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2+p3,mt)*
 glprop(11,12,-k1-p4+p2,0)*
 fpropu(13,14,-k1+k2-p1,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(Uug,4,k1,11,-k1-p4+p2,1,p4-p2)*
 vrtx(Uug,14,k1-k2+p1,6,-k1-p1,7,k2)*
 vrtx(Uug,10,-k2-p3,12,k1+p4-p2,13,-k1+k2-p1)
;
Local loop2diagram50=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 glprop(11,12,-k1-p4+p2,0)*
 glprop(13,14,k1-k2+p1,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,4,k1,11,-k1-p4+p2,1,p4-p2)*
 vrtx(ggg,6,-k1-p1,8,k2,13,k1-k2+p1)*
 vrtx(ggg,12,k1+p4-p2,10,-k2-p3,14,-k1+k2-p1)
;
Local loop2diagram51=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 ghprop(7,8,-k2,0)*
 ghprop(9,10,-k2-p3,0)*
 glprop(11,12,-k1-p4+p2,0)*
 ghprop(13,14,k1-k2+p1,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Ghghg,10,k2+p3,-6,-p3,7,-k2)*
 vrtx(Uug,4,k1,11,-k1-p4+p2,1,p4-p2)*
 vrtx(Ghghg,8,k2,6,-k1-p1,13,k1-k2+p1)*
 vrtx(Ghghg,14,-k1+k2-p1,12,k1+p4-p2,9,-k2-p3)
;
Local loop2diagram52=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 ghprop(7,8,k2,0)*
 ghprop(9,10,k2+p3,0)*
 glprop(11,12,-k1-p4+p2,0)*
 ghprop(13,14,-k1+k2-p1,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Ghghg,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(Uug,4,k1,11,-k1-p4+p2,1,p4-p2)*
 vrtx(Ghghg,14,k1-k2+p1,6,-k1-p1,7,k2)*
 vrtx(Ghghg,10,-k2-p3,12,k1+p4-p2,13,-k1+k2-p1)
;
Local loop2diagram53=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2+p3,mt)*
 fpropu(11,12,k1+p4-p2,mt)*
 glprop(13,14,k1-k2+p1,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(Uug,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(Uug,12,-k1-p4+p2,4,k1,1,p4-p2)*
 vrtx(Uug,6,-k1-p1,13,k1-k2+p1,7,k2)*
 vrtx(Uug,10,-k2-p3,14,-k1+k2-p1,11,k1+p4-p2)
;
Local loop2diagram54=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,k1+p4-p2,mt)*
 fpropu(13,14,k1-k2+p1,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,12,-k1-p4+p2,4,k1,1,p4-p2)*
 vrtx(Uug,6,-k1-p1,8,k2,13,k1-k2+p1)*
 vrtx(Uug,14,-k1+k2-p1,10,-k2-p3,11,k1+p4-p2)
;
Local loop2diagram55=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1-p3,mt)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,-k1-p4+p2,0)*
 glprop(13,14,k1-k2+p3,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,6,k1+p3,-6,-p3,3,-k1)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,4,k1,11,-k1-p4+p2,1,p4-p2)*
 vrtx(Uug,8,k2,13,k1-k2+p3,5,-k1-p3)*
 vrtx(ggg,12,k1+p4-p2,10,-k2-p1,14,-k1+k2-p3)
;
Local loop2diagram56=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1-p3,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 glprop(11,12,-k1-p4+p2,0)*
 fpropu(13,14,-k1+k2-p3,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,6,k1+p3,-6,-p3,3,-k1)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,4,k1,11,-k1-p4+p2,1,p4-p2)*
 vrtx(Uug,14,k1-k2+p3,8,k2,5,-k1-p3)*
 vrtx(Uug,10,-k2-p1,12,k1+p4-p2,13,-k1+k2-p3)
;
Local loop2diagram57=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 glprop(5,6,k1+p3,0)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 fpropu(11,12,k1+p4-p2,mt)*
 fpropu(13,14,k1-k2+p3,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(ggg,-6,-p3,3,-k1,5,k1+p3)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,12,-k1-p4+p2,4,k1,1,p4-p2)*
 vrtx(Uug,8,k2,6,-k1-p3,13,k1-k2+p3)*
 vrtx(Uug,14,-k1+k2-p3,10,-k2-p1,11,k1+p4-p2)
;
Local loop2diagram58=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 glprop(5,6,k1+p3,0)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 fpropu(11,12,k1+p4-p2,mt)*
 glprop(13,14,k1-k2+p3,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(ggg,-6,-p3,3,-k1,5,k1+p3)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,12,-k1-p4+p2,4,k1,1,p4-p2)*
 vrtx(ggg,6,-k1-p3,8,k2,13,k1-k2+p3)*
 vrtx(Uug,10,-k2-p1,14,-k1+k2-p3,11,k1+p4-p2)
;
Local loop2diagram59=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2-p3,mt)*
 fpropu(11,12,-k1+p1+p2,mt)*
 glprop(13,14,k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,10,k2+p3,-6,-p3,7,-k2)*
 vrtx(Uug,4,k1,2,-p1-p2,11,-k1+p1+p2)*
 vrtx(Uug,8,k2,13,k1-k2-p4,5,-k1+p4)*
 vrtx(Uug,12,k1-p1-p2,14,-k1+k2+p4,9,-k2-p3)
;
Local loop2diagram60=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,-k1+p1+p2,mt)*
 fpropu(13,14,-k1+k2+p4,mt)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,4,k1,2,-p1-p2,11,-k1+p1+p2)*
 vrtx(Uug,14,k1-k2-p4,8,k2,5,-k1+p4)*
 vrtx(Uug,12,k1-p1-p2,10,-k2-p3,13,-k1+k2+p4)
;
Local loop2diagram61=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2+p3,mt)*
 fpropu(11,12,k1-p1-p2,mt)*
 glprop(13,14,k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(Uug,12,-k1+p1+p2,2,-p1-p2,3,k1)*
 vrtx(Uug,6,-k1+p4,13,k1-k2-p4,7,k2)*
 vrtx(Uug,10,-k2-p3,14,-k1+k2+p4,11,k1-p1-p2)
;
Local loop2diagram62=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,k1-p1-p2,mt)*
 fpropu(13,14,k1-k2-p4,mt)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,12,-k1+p1+p2,2,-p1-p2,3,k1)*
 vrtx(Uug,6,-k1+p4,8,k2,13,k1-k2-p4)*
 vrtx(Uug,14,-k1+k2+p4,10,-k2-p3,11,k1-p1-p2)
;
Local loop2diagram63=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1-p3,mt)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2+p4,mt)*
 fpropu(11,12,-k1+p1+p2,mt)*
 glprop(13,14,k1-k2+p3,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uug,6,k1+p3,-6,-p3,3,-k1)*
 vrtx(Uup,10,k2-p4,-1,p4,7,-k2)*
 vrtx(Uug,4,k1,2,-p1-p2,11,-k1+p1+p2)*
 vrtx(Uug,8,k2,13,k1-k2+p3,5,-k1-p3)*
 vrtx(Uug,12,k1-p1-p2,14,-k1+k2-p3,9,-k2+p4)
;
Local loop2diagram64=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1+p3,mt)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 fpropu(11,12,k1-p1-p2,mt)*
 glprop(13,14,k1-k2+p3,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uug,4,-k1,-6,-p3,5,k1+p3)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(Uug,12,-k1+p1+p2,2,-p1-p2,3,k1)*
 vrtx(Uug,6,-k1-p3,13,k1-k2+p3,7,k2)*
 vrtx(Uug,10,-k2+p4,14,-k1+k2-p3,11,k1-p1-p2)
;
Local loop2diagram65=

 -(1)*
 glprop(1,2,p1+p2,0)*
 glprop(3,4,-k1,0)*
 glprop(5,6,k1+p3,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2+p4,mt)*
 glprop(11,12,-k1+p1+p2,0)*
 fpropu(13,14,k1-k2+p3,mt)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,3,-k1,5,k1+p3)*
 vrtx(Uup,10,k2-p4,-1,p4,7,-k2)*
 vrtx(ggg,2,-p1-p2,4,k1,11,-k1+p1+p2)*
 vrtx(Uug,8,k2,6,-k1-p3,13,k1-k2+p3)*
 vrtx(Uug,14,-k1+k2-p3,12,k1-p1-p2,9,-k2+p4)
;
Local loop2diagram66=

 -(1)*
 glprop(1,2,p1+p2,0)*
 glprop(3,4,-k1,0)*
 glprop(5,6,k1+p3,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 glprop(11,12,-k1+p1+p2,0)*
 fpropu(13,14,-k1+k2-p3,mt)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,3,-k1,5,k1+p3)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(ggg,2,-p1-p2,4,k1,11,-k1+p1+p2)*
 vrtx(Uug,14,k1-k2+p3,6,-k1-p3,7,k2)*
 vrtx(Uug,10,-k2+p4,12,k1-p1-p2,13,-k1+k2-p3)
;
Local loop2diagram67=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 glprop(11,12,-k1+p1+p3,0)*
 glprop(13,14,k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,11,-k1+p1+p3,3,k1)*
 vrtx(Uug,6,-k1+p4,13,k1-k2-p4,7,k2)*
 vrtx(ggg,12,k1-p1-p3,10,-k2-p2,14,-k1+k2+p4)
;
Local loop2diagram68=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,-k2-p2,mt)*
 glprop(11,12,-k1+p1+p3,0)*
 fpropu(13,14,k1-k2-p4,mt)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,10,k2+p2,7,-k2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,11,-k1+p1+p3,3,k1)*
 vrtx(Uug,6,-k1+p4,8,k2,13,k1-k2-p4)*
 vrtx(Uug,14,-k1+k2+p4,12,k1-p1-p3,9,-k2-p2)
;
Local loop2diagram69=

 -(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2+p4,mt)*
 glprop(11,12,-k1+p1+p3,0)*
 fpropu(13,14,k1-k2+p2,mt)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uup,10,k2-p4,-1,p4,7,-k2)*
 vrtx(Uug,2,-p1-p3,11,-k1+p1+p3,3,k1)*
 vrtx(Uug,8,k2,6,-k1-p2,13,k1-k2+p2)*
 vrtx(Uug,14,-k1+k2-p2,12,k1-p1-p3,9,-k2+p4)
;
Local loop2diagram70=

 -(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 glprop(11,12,-k1+p1+p3,0)*
 fpropu(13,14,-k1+k2-p2,mt)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(Uug,2,-p1-p3,11,-k1+p1+p3,3,k1)*
 vrtx(Uug,14,k1-k2+p2,6,-k1-p2,7,k2)*
 vrtx(Uug,10,-k2+p4,12,k1-p1-p3,13,-k1+k2-p2)
;
Local loop2diagram71=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2+p4,mt)*
 fpropu(11,12,-k1+p1+p3,mt)*
 glprop(13,14,k1-k2+p2,0)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(Uup,10,k2-p4,-1,p4,7,-k2)*
 vrtx(Uug,2,-p1-p3,4,k1,11,-k1+p1+p3)*
 vrtx(Uug,8,k2,13,k1-k2+p2,5,-k1-p2)*
 vrtx(Uug,12,k1-p1-p3,14,-k1+k2-p2,9,-k2+p4)
;
Local loop2diagram72=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,-k1+p2+p3,0)*
 glprop(13,14,k1-k2-p4,0)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,4,k1,11,-k1+p2+p3,1,-p2-p3)*
 vrtx(Uug,8,k2,13,k1-k2-p4,5,-k1+p4)*
 vrtx(ggg,12,k1-p2-p3,10,-k2-p1,14,-k1+k2+p4)
;
Local loop2diagram73=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 glprop(11,12,-k1+p2+p3,0)*
 fpropu(13,14,-k1+k2+p4,mt)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,4,k1,11,-k1+p2+p3,1,-p2-p3)*
 vrtx(Uug,14,k1-k2-p4,8,k2,5,-k1+p4)*
 vrtx(Uug,10,-k2-p1,12,k1-p2-p3,13,-k1+k2+p4)
;
Local loop2diagram74=

 -(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2+p4,mt)*
 glprop(11,12,-k1+p2+p3,0)*
 fpropu(13,14,k1-k2+p1,mt)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uup,10,k2-p4,-1,p4,7,-k2)*
 vrtx(Uug,4,k1,11,-k1+p2+p3,1,-p2-p3)*
 vrtx(Uug,8,k2,6,-k1-p1,13,k1-k2+p1)*
 vrtx(Uug,14,-k1+k2-p1,12,k1-p2-p3,9,-k2+p4)
;
Local loop2diagram75=

 -(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 glprop(11,12,-k1+p2+p3,0)*
 fpropu(13,14,-k1+k2-p1,mt)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(Uug,4,k1,11,-k1+p2+p3,1,-p2-p3)*
 vrtx(Uug,14,k1-k2+p1,6,-k1-p1,7,k2)*
 vrtx(Uug,10,-k2+p4,12,k1-p2-p3,13,-k1+k2-p1)
;
Local loop2diagram76=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 fpropu(11,12,k1-p2-p3,mt)*
 glprop(13,14,k1-k2+p1,0)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(Uug,12,-k1+p2+p3,4,k1,1,-p2-p3)*
 vrtx(Uug,6,-k1-p1,13,k1-k2+p1,7,k2)*
 vrtx(Uug,10,-k2+p4,14,-k1+k2-p1,11,k1-p2-p3)
;
Local loop2diagram77=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 glprop(7,8,k1+p4-p1,0)*
 glprop(9,10,-k1-p2,0)*
 fpropu(11,12,k1+k2+p2,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,7,k1+p4-p1,9,-k1-p2)*
 vrtx(Uug,2,p4-p1,8,-k1-p4+p1,3,k1)*
 vrtx(Uug,14,-k2,6,-k1-p2,11,k1+k2+p2)*
 vrtx(Uug,12,-k1-k2-p2,10,k1+p2,13,k2)
;
Local loop2diagram78=

 +(1/2)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 glprop(7,8,k1+p4-p1,0)*
 glprop(9,10,-k1-p2,0)*
 glprop(11,12,k1+k2+p2,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,7,k1+p4-p1,9,-k1-p2)*
 vrtx(Uug,2,p4-p1,8,-k1-p4+p1,3,k1)*
 vrtx(ggg,6,-k1-p2,11,k1+k2+p2,13,-k2)*
 vrtx(ggg,10,k1+p2,12,-k1-k2-p2,14,k2)
;
Local loop2diagram79=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 glprop(7,8,k1+p4-p1,0)*
 glprop(9,10,-k1-p2,0)*
 ghprop(11,12,k1+k2+p2,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,7,k1+p4-p1,9,-k1-p2)*
 vrtx(Uug,2,p4-p1,8,-k1-p4+p1,3,k1)*
 vrtx(Ghghg,14,-k2,6,-k1-p2,11,k1+k2+p2)*
 vrtx(Ghghg,12,-k1-k2-p2,10,k1+p2,13,k2)
;
Local loop2diagram80=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 fpropu(7,8,-k1-p4+p1,mt)*
 fpropu(9,10,-k1-p2,mt)*
 fpropu(11,12,-k1-k2-p2,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(Uug,8,k1+p4-p1,-6,-p3,9,-k1-p2)*
 vrtx(Uug,2,p4-p1,4,k1,7,-k1-p4+p1)*
 vrtx(Uug,12,k1+k2+p2,13,-k2,5,-k1-p2)*
 vrtx(Uug,10,k1+p2,14,k2,11,-k1-k2-p2)
;
Local loop2diagram81=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 glprop(7,8,k1+p4-p2,0)*
 glprop(9,10,-k1-p1,0)*
 fpropu(11,12,k1+k2+p1,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(ggg,-6,-p3,7,k1+p4-p2,9,-k1-p1)*
 vrtx(Uug,4,k1,8,-k1-p4+p2,1,p4-p2)*
 vrtx(Uug,14,-k2,6,-k1-p1,11,k1+k2+p1)*
 vrtx(Uug,12,-k1-k2-p1,10,k1+p1,13,k2)
;
Local loop2diagram82=

 +(1/2)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 glprop(7,8,k1+p4-p2,0)*
 glprop(9,10,-k1-p1,0)*
 glprop(11,12,k1+k2+p1,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(ggg,-6,-p3,7,k1+p4-p2,9,-k1-p1)*
 vrtx(Uug,4,k1,8,-k1-p4+p2,1,p4-p2)*
 vrtx(ggg,6,-k1-p1,11,k1+k2+p1,13,-k2)*
 vrtx(ggg,10,k1+p1,12,-k1-k2-p1,14,k2)
;
Local loop2diagram83=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 glprop(7,8,k1+p4-p2,0)*
 glprop(9,10,-k1-p1,0)*
 ghprop(11,12,k1+k2+p1,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(ggg,-6,-p3,7,k1+p4-p2,9,-k1-p1)*
 vrtx(Uug,4,k1,8,-k1-p4+p2,1,p4-p2)*
 vrtx(Ghghg,14,-k2,6,-k1-p1,11,k1+k2+p1)*
 vrtx(Ghghg,12,-k1-k2-p1,10,k1+p1,13,k2)
;
Local loop2diagram84=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 fpropu(7,8,k1+p4-p2,mt)*
 fpropu(9,10,k1+p1,mt)*
 fpropu(11,12,k1+k2+p1,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(Uug,10,-k1-p1,-6,-p3,7,k1+p4-p2)*
 vrtx(Uug,8,-k1-p4+p2,4,k1,1,p4-p2)*
 vrtx(Uug,6,-k1-p1,13,-k2,11,k1+k2+p1)*
 vrtx(Uug,12,-k1-k2-p1,14,k2,9,k1+p1)
;
Local loop2diagram85=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k1+p1+p2,mt)*
 fpropu(9,10,-k1+p4,mt)*
 fpropu(11,12,-k1-k2+p4,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,8,k1-p1-p2,-6,-p3,9,-k1+p4)*
 vrtx(Uug,4,k1,2,-p1-p2,7,-k1+p1+p2)*
 vrtx(Uug,12,k1+k2-p4,13,-k2,5,-k1+p4)*
 vrtx(Uug,10,k1-p4,14,k2,11,-k1-k2+p4)
;
Local loop2diagram86=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k1-p1-p2,mt)*
 fpropu(9,10,k1-p4,mt)*
 fpropu(11,12,k1+k2-p4,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,10,-k1+p4,-6,-p3,7,k1-p1-p2)*
 vrtx(Uug,8,-k1+p1+p2,2,-p1-p2,3,k1)*
 vrtx(Uug,6,-k1+p4,13,-k2,11,k1+k2-p4)*
 vrtx(Uug,12,-k1-k2+p4,14,k2,9,k1-p4)
;
Local loop2diagram87=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,k1-p1-p3,0)*
 fpropu(9,10,k1-p4,mt)*
 fpropu(11,12,k1+k2-p4,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,10,-k1+p4,7,k1-p1-p3,-4,-p2)*
 vrtx(Uug,2,-p1-p3,8,-k1+p1+p3,3,k1)*
 vrtx(Uug,6,-k1+p4,13,-k2,11,k1+k2-p4)*
 vrtx(Uug,12,-k1-k2+p4,14,k2,9,k1-p4)
;
Local loop2diagram88=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,k1-p2-p3,0)*
 fpropu(9,10,-k1+p4,mt)*
 fpropu(11,12,-k1-k2+p4,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,-2,-p1,7,k1-p2-p3,9,-k1+p4)*
 vrtx(Uug,4,k1,8,-k1+p2+p3,1,-p2-p3)*
 vrtx(Uug,12,k1+k2-p4,13,-k2,5,-k1+p4)*
 vrtx(Uug,10,k1-p4,14,k2,11,-k1-k2+p4)
;
Local loop2diagram89=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,k1-p3,mt)*
 fpropu(9,10,-k2,mt)*
 glprop(11,12,k2-p4+p1,0)*
 fpropu(13,14,k1-k2+p2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(Uug,2,p4-p1,11,k2-p4+p1,9,-k2)*
 vrtx(Uug,10,k2,6,-k1-p2,13,k1-k2+p2)*
 vrtx(Uug,14,-k1+k2-p2,12,-k2+p4-p1,7,k1-p3)
;
Local loop2diagram90=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,k1-p3,mt)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,k2-p4+p1,mt)*
 glprop(13,14,k1-k2+p2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(Uug,2,p4-p1,9,-k2,11,k2-p4+p1)*
 vrtx(ggg,6,-k1-p2,10,k2,13,k1-k2+p2)*
 vrtx(Uug,12,-k2+p4-p1,14,-k1+k2-p2,7,k1-p3)
;
Local loop2diagram91=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 glprop(7,8,-k1+p3,0)*
 fpropu(9,10,-k2,mt)*
 glprop(11,12,k2-p4+p1,0)*
 glprop(13,14,k1-k2+p2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,2,p4-p1,11,k2-p4+p1,9,-k2)*
 vrtx(Uug,10,k2,13,k1-k2+p2,5,-k1-p2)*
 vrtx(ggg,8,k1-p3,12,-k2+p4-p1,14,-k1+k2-p2)
;
Local loop2diagram92=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 glprop(7,8,-k1+p3,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,k2-p4+p1,mt)*
 fpropu(13,14,-k1+k2-p2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,2,p4-p1,9,-k2,11,k2-p4+p1)*
 vrtx(Uug,14,k1-k2+p2,10,k2,5,-k1-p2)*
 vrtx(Uug,12,-k2+p4-p1,8,k1-p3,13,-k1+k2-p2)
;
Local loop2diagram93=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,-k1+p3,mt)*
 fpropu(9,10,k2,mt)*
 glprop(11,12,k2-p4+p2,0)*
 fpropu(13,14,-k1+k2-p1,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(Uug,10,-k2,11,k2-p4+p2,1,p4-p2)*
 vrtx(Uug,14,k1-k2+p1,6,-k1-p1,9,k2)*
 vrtx(Uug,8,k1-p3,12,-k2+p4-p2,13,-k1+k2-p1)
;
Local loop2diagram94=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,-k1+p3,mt)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,-k2+p4-p2,mt)*
 glprop(13,14,k1-k2+p1,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(Uug,12,k2-p4+p2,9,-k2,1,p4-p2)*
 vrtx(ggg,6,-k1-p1,10,k2,13,k1-k2+p1)*
 vrtx(Uug,8,k1-p3,14,-k1+k2-p1,11,-k2+p4-p2)
;
Local loop2diagram95=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 glprop(7,8,-k1+p3,0)*
 fpropu(9,10,k2,mt)*
 glprop(11,12,k2-p4+p2,0)*
 glprop(13,14,k1-k2+p1,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,10,-k2,11,k2-p4+p2,1,p4-p2)*
 vrtx(Uug,6,-k1-p1,13,k1-k2+p1,9,k2)*
 vrtx(ggg,8,k1-p3,12,-k2+p4-p2,14,-k1+k2-p1)
;
Local loop2diagram96=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 glprop(7,8,-k1+p3,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,-k2+p4-p2,mt)*
 fpropu(13,14,k1-k2+p1,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,12,k2-p4+p2,9,-k2,1,p4-p2)*
 vrtx(Uug,6,-k1-p1,10,k2,13,k1-k2+p1)*
 vrtx(Uug,14,-k1+k2-p1,8,k1-p3,11,-k2+p4-p2)
;
Local loop2diagram97=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k1+p3,mt)*
 fpropu(9,10,-k2,mt)*
 fpropu(11,12,-k2-p1-p2,mt)*
 glprop(13,14,k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(Uug,12,k2+p1+p2,2,-p1-p2,9,-k2)*
 vrtx(Uug,10,k2,13,k1-k2-p4,5,-k1+p4)*
 vrtx(Uug,8,k1-p3,14,-k1+k2+p4,11,-k2-p1-p2)
;
Local loop2diagram98=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k1+p3,mt)*
 glprop(9,10,-k2,0)*
 glprop(11,12,k2+p1+p2,0)*
 fpropu(13,14,-k1+k2+p4,mt)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(ggg,2,-p1-p2,9,-k2,11,k2+p1+p2)*
 vrtx(Uug,14,k1-k2-p4,10,k2,5,-k1+p4)*
 vrtx(Uug,8,k1-p3,12,-k2-p1-p2,13,-k1+k2+p4)
;
Local loop2diagram99=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k1-p3,mt)*
 fpropu(9,10,k2,mt)*
 fpropu(11,12,k2+p1+p2,mt)*
 glprop(13,14,k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(Uug,10,-k2,2,-p1-p2,11,k2+p1+p2)*
 vrtx(Uug,6,-k1+p4,13,k1-k2-p4,9,k2)*
 vrtx(Uug,12,-k2-p1-p2,14,-k1+k2+p4,7,k1-p3)
;
Local loop2diagram100=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k1-p3,mt)*
 glprop(9,10,-k2,0)*
 glprop(11,12,k2+p1+p2,0)*
 fpropu(13,14,k1-k2-p4,mt)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(ggg,2,-p1-p2,9,-k2,11,k2+p1+p2)*
 vrtx(Uug,6,-k1+p4,10,k2,13,k1-k2-p4)*
 vrtx(Uug,14,-k1+k2+p4,12,-k2-p1-p2,7,k1-p3)
;
Local loop2diagram101=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k1+p2,0)*
 fpropu(9,10,-k2,mt)*
 glprop(11,12,k2+p1+p3,0)*
 glprop(13,14,k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,11,k2+p1+p3,9,-k2)*
 vrtx(Uug,10,k2,13,k1-k2-p4,5,-k1+p4)*
 vrtx(ggg,8,k1-p2,12,-k2-p1-p3,14,-k1+k2+p4)
;
Local loop2diagram102=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k1+p2,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,k2+p1+p3,mt)*
 fpropu(13,14,-k1+k2+p4,mt)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,9,-k2,11,k2+p1+p3)*
 vrtx(Uug,14,k1-k2-p4,10,k2,5,-k1+p4)*
 vrtx(Uug,12,-k2-p1-p3,8,k1-p2,13,-k1+k2+p4)
;
Local loop2diagram103=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,-k1+p1,0)*
 fpropu(9,10,k2,mt)*
 glprop(11,12,k2+p2+p3,0)*
 glprop(13,14,k1-k2-p4,0)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,10,-k2,11,k2+p2+p3,1,-p2-p3)*
 vrtx(Uug,6,-k1+p4,13,k1-k2-p4,9,k2)*
 vrtx(ggg,8,k1-p1,12,-k2-p2-p3,14,-k1+k2+p4)
;
Local loop2diagram104=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,-k1+p1,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,-k2-p2-p3,mt)*
 fpropu(13,14,k1-k2-p4,mt)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,12,k2+p2+p3,9,-k2,1,-p2-p3)*
 vrtx(Uug,6,-k1+p4,10,k2,13,k1-k2-p4)*
 vrtx(Uug,14,-k1+k2+p4,8,k1-p1,11,-k2-p2-p3)
;
Local loop2diagram105=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,k1-p3,mt)*
 fpropu(9,10,k2-p4+p1,mt)*
 glprop(11,12,-k2,0)*
 fpropu(13,14,-p2-p3,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(Uug,2,p4-p1,11,-k2,9,k2-p4+p1)*
 vrtx(Uug,14,p2+p3,6,-k1-p2,7,k1-p3)*
 vrtx(Uug,10,-k2+p4-p1,12,k2,13,-p2-p3)
;
Local loop2diagram106=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 glprop(7,8,-k1+p3,0)*
 fpropu(9,10,k2-p4+p1,mt)*
 glprop(11,12,-k2,0)*
 fpropu(13,14,-p2-p3,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,2,p4-p1,11,-k2,9,k2-p4+p1)*
 vrtx(Uug,14,p2+p3,8,k1-p3,5,-k1-p2)*
 vrtx(Uug,10,-k2+p4-p1,12,k2,13,-p2-p3)
;
Local loop2diagram107=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,-k1+p3,mt)*
 fpropu(9,10,-k2+p4-p2,mt)*
 glprop(11,12,-k2,0)*
 fpropu(13,14,p1+p3,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(Uug,10,k2-p4+p2,11,-k2,1,p4-p2)*
 vrtx(Uug,8,k1-p3,6,-k1-p1,13,p1+p3)*
 vrtx(Uug,14,-p1-p3,12,k2,9,-k2+p4-p2)
;
Local loop2diagram108=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 glprop(7,8,-k1+p3,0)*
 fpropu(9,10,-k2+p4-p2,mt)*
 glprop(11,12,-k2,0)*
 fpropu(13,14,p1+p3,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,10,k2-p4+p2,11,-k2,1,p4-p2)*
 vrtx(Uug,6,-k1-p1,8,k1-p3,13,p1+p3)*
 vrtx(Uug,14,-p1-p3,12,k2,9,-k2+p4-p2)
;
Local loop2diagram109=

 +(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k1+p3,mt)*
 fpropu(9,10,k2+p1+p2,mt)*
 fpropu(11,12,k2,mt)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(Uug,12,-k2,2,-p1-p2,9,k2+p1+p2)*
 vrtx(Uug,8,k1-p3,13,-p4+p3,5,-k1+p4)*
 vrtx(Uug,10,-k2-p1-p2,14,p4-p3,11,k2)
;
Local loop2diagram110=

 -(1/2)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k1+p3,mt)*
 glprop(9,10,k2+p1+p2,0)*
 glprop(11,12,-k2,0)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(ggg,2,-p1-p2,9,k2+p1+p2,11,-k2)*
 vrtx(Uug,8,k1-p3,13,-p4+p3,5,-k1+p4)*
 vrtx(ggg,14,p4-p3,10,-k2-p1-p2,12,k2)
;
Local loop2diagram111=

 +(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k1+p3,mt)*
 ghprop(9,10,k2+p1+p2,0)*
 ghprop(11,12,k2,0)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(Ghghg,12,-k2,2,-p1-p2,9,k2+p1+p2)*
 vrtx(Uug,8,k1-p3,13,-p4+p3,5,-k1+p4)*
 vrtx(Ghghg,10,-k2-p1-p2,14,p4-p3,11,k2)
;
Local loop2diagram112=

 +(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k1-p3,mt)*
 fpropu(9,10,k2+p1+p2,mt)*
 fpropu(11,12,k2,mt)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(Uug,12,-k2,2,-p1-p2,9,k2+p1+p2)*
 vrtx(Uug,6,-k1+p4,13,-p4+p3,7,k1-p3)*
 vrtx(Uug,10,-k2-p1-p2,14,p4-p3,11,k2)
;
Local loop2diagram113=

 -(1/2)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k1-p3,mt)*
 glprop(9,10,k2+p1+p2,0)*
 glprop(11,12,-k2,0)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(ggg,2,-p1-p2,9,k2+p1+p2,11,-k2)*
 vrtx(Uug,6,-k1+p4,13,-p4+p3,7,k1-p3)*
 vrtx(ggg,14,p4-p3,10,-k2-p1-p2,12,k2)
;
Local loop2diagram114=

 +(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k1-p3,mt)*
 ghprop(9,10,k2+p1+p2,0)*
 ghprop(11,12,k2,0)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(Ghghg,12,-k2,2,-p1-p2,9,k2+p1+p2)*
 vrtx(Uug,6,-k1+p4,13,-p4+p3,7,k1-p3)*
 vrtx(Ghghg,10,-k2-p1-p2,14,p4-p3,11,k2)
;
Local loop2diagram115=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k1+p2,0)*
 fpropu(9,10,k2+p1+p3,mt)*
 glprop(11,12,-k2,0)*
 fpropu(13,14,p4-p2,mt)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,11,-k2,9,k2+p1+p3)*
 vrtx(Uug,14,-p4+p2,8,k1-p2,5,-k1+p4)*
 vrtx(Uug,10,-k2-p1-p3,12,k2,13,p4-p2)
;
Local loop2diagram116=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,-k1+p1,0)*
 fpropu(9,10,-k2-p2-p3,mt)*
 glprop(11,12,-k2,0)*
 fpropu(13,14,-p4+p1,mt)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,10,k2+p2+p3,11,-k2,1,-p2-p3)*
 vrtx(Uug,6,-k1+p4,8,k1-p1,13,-p4+p1)*
 vrtx(Uug,14,p4-p1,12,k2,9,-k2-p2-p3)
;
Local loop2diagram117=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,k1-p3,mt)*
 fpropu(9,10,k1-p3,mt)*
 fpropu(11,12,k1-k2-p3,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(Uug,2,p4-p1,6,-k1-p2,9,k1-p3)*
 vrtx(Uug,12,-k1+k2+p3,13,-k2,7,k1-p3)*
 vrtx(Uug,10,-k1+p3,14,k2,11,k1-k2-p3)
;
Local loop2diagram118=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 glprop(7,8,-k1+p3,0)*
 glprop(9,10,k1-p3,0)*
 fpropu(11,12,-k1+k2+p3,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,2,p4-p1,9,k1-p3,5,-k1-p2)*
 vrtx(Uug,14,-k2,8,k1-p3,11,-k1+k2+p3)*
 vrtx(Uug,12,k1-k2-p3,10,-k1+p3,13,k2)
;
Local loop2diagram119=

 +(1/2)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 glprop(7,8,-k1+p3,0)*
 glprop(9,10,k1-p3,0)*
 glprop(11,12,-k1+k2+p3,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,2,p4-p1,9,k1-p3,5,-k1-p2)*
 vrtx(ggg,8,k1-p3,11,-k1+k2+p3,13,-k2)*
 vrtx(ggg,10,-k1+p3,12,k1-k2-p3,14,k2)
;
Local loop2diagram120=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,-k1-p2,mt)*
 glprop(7,8,-k1+p3,0)*
 glprop(9,10,k1-p3,0)*
 ghprop(11,12,-k1+k2+p3,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p2,3,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,2,p4-p1,9,k1-p3,5,-k1-p2)*
 vrtx(Ghghg,14,-k2,8,k1-p3,11,-k1+k2+p3)*
 vrtx(Ghghg,12,k1-k2-p3,10,-k1+p3,13,k2)
;
Local loop2diagram121=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1-p3,mt)*
 glprop(7,8,-k1+p2,0)*
 glprop(9,10,k1-p2,0)*
 fpropu(11,12,-k1+k2+p2,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p3,-6,-p3,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,p4-p1,9,k1-p2,5,-k1-p3)*
 vrtx(Uug,14,-k2,8,k1-p2,11,-k1+k2+p2)*
 vrtx(Uug,12,k1-k2-p2,10,-k1+p2,13,k2)
;
Local loop2diagram122=

 +(1/2)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1-p3,mt)*
 glprop(7,8,-k1+p2,0)*
 glprop(9,10,k1-p2,0)*
 glprop(11,12,-k1+k2+p2,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p3,-6,-p3,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,p4-p1,9,k1-p2,5,-k1-p3)*
 vrtx(ggg,8,k1-p2,11,-k1+k2+p2,13,-k2)*
 vrtx(ggg,10,-k1+p2,12,k1-k2-p2,14,k2)
;
Local loop2diagram123=

 -(1)*
 fpropu(1,2,-p4+p1,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1-p3,mt)*
 glprop(7,8,-k1+p2,0)*
 glprop(9,10,k1-p2,0)*
 ghprop(11,12,-k1+k2+p2,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(Uug,6,k1+p3,-6,-p3,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,p4-p1,9,k1-p2,5,-k1-p3)*
 vrtx(Ghghg,14,-k2,8,k1-p2,11,-k1+k2+p2)*
 vrtx(Ghghg,12,k1-k2-p2,10,-k1+p2,13,k2)
;
Local loop2diagram124=

 +(1)*
 fpropu(1,2,-p4+p1,mt)*
 glprop(3,4,-k1,0)*
 glprop(5,6,k1+p3,0)*
 fpropu(7,8,k1-p2,mt)*
 fpropu(9,10,k1-p2,mt)*
 fpropu(11,12,k1-k2-p2,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,-2,-p1,-1,p4,1,-p4+p1)*
 vrtx(ggg,-6,-p3,3,-k1,5,k1+p3)*
 vrtx(Uug,8,-k1+p2,4,k1,-4,-p2)*
 vrtx(Uug,2,p4-p1,6,-k1-p3,9,k1-p2)*
 vrtx(Uug,12,-k1+k2+p2,13,-k2,7,k1-p2)*
 vrtx(Uug,10,-k1+p2,14,k2,11,k1-k2-p2)
;
Local loop2diagram125=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,-k1+p3,mt)*
 fpropu(9,10,-k1+p3,mt)*
 fpropu(11,12,-k1+k2+p3,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(Uug,10,k1-p3,6,-k1-p1,1,p4-p2)*
 vrtx(Uug,8,k1-p3,13,-k2,11,-k1+k2+p3)*
 vrtx(Uug,12,k1-k2-p3,14,k2,9,-k1+p3)
;
Local loop2diagram126=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 glprop(7,8,-k1+p3,0)*
 glprop(9,10,k1-p3,0)*
 fpropu(11,12,-k1+k2+p3,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,6,-k1-p1,9,k1-p3,1,p4-p2)*
 vrtx(Uug,14,-k2,8,k1-p3,11,-k1+k2+p3)*
 vrtx(Uug,12,k1-k2-p3,10,-k1+p3,13,k2)
;
Local loop2diagram127=

 +(1/2)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 glprop(7,8,-k1+p3,0)*
 glprop(9,10,k1-p3,0)*
 glprop(11,12,-k1+k2+p3,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,6,-k1-p1,9,k1-p3,1,p4-p2)*
 vrtx(ggg,8,k1-p3,11,-k1+k2+p3,13,-k2)*
 vrtx(ggg,10,-k1+p3,12,k1-k2-p3,14,k2)
;
Local loop2diagram128=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 fpropu(5,6,k1+p1,mt)*
 glprop(7,8,-k1+p3,0)*
 glprop(9,10,k1-p3,0)*
 ghprop(11,12,-k1+k2+p3,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,-2,-p1,3,-k1,5,k1+p1)*
 vrtx(ggg,-6,-p3,4,k1,7,-k1+p3)*
 vrtx(Uug,6,-k1-p1,9,k1-p3,1,p4-p2)*
 vrtx(Ghghg,14,-k2,8,k1-p3,11,-k1+k2+p3)*
 vrtx(Ghghg,12,k1-k2-p3,10,-k1+p3,13,k2)
;
Local loop2diagram129=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1+p3,mt)*
 glprop(7,8,-k1+p1,0)*
 glprop(9,10,k1-p1,0)*
 fpropu(11,12,-k1+k2+p1,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,4,-k1,-6,-p3,5,k1+p3)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,6,-k1-p3,9,k1-p1,1,p4-p2)*
 vrtx(Uug,14,-k2,8,k1-p1,11,-k1+k2+p1)*
 vrtx(Uug,12,k1-k2-p1,10,-k1+p1,13,k2)
;
Local loop2diagram130=

 +(1/2)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1+p3,mt)*
 glprop(7,8,-k1+p1,0)*
 glprop(9,10,k1-p1,0)*
 glprop(11,12,-k1+k2+p1,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,4,-k1,-6,-p3,5,k1+p3)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,6,-k1-p3,9,k1-p1,1,p4-p2)*
 vrtx(ggg,8,k1-p1,11,-k1+k2+p1,13,-k2)*
 vrtx(ggg,10,-k1+p1,12,k1-k2-p1,14,k2)
;
Local loop2diagram131=

 -(1)*
 fpropu(1,2,p4-p2,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1+p3,mt)*
 glprop(7,8,-k1+p1,0)*
 glprop(9,10,k1-p1,0)*
 ghprop(11,12,-k1+k2+p1,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(Uug,4,-k1,-6,-p3,5,k1+p3)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,6,-k1-p3,9,k1-p1,1,p4-p2)*
 vrtx(Ghghg,14,-k2,8,k1-p1,11,-k1+k2+p1)*
 vrtx(Ghghg,12,k1-k2-p1,10,-k1+p1,13,k2)
;
Local loop2diagram132=

 +(1)*
 fpropu(1,2,p4-p2,mt)*
 glprop(3,4,-k1,0)*
 glprop(5,6,k1+p3,0)*
 fpropu(7,8,-k1+p1,mt)*
 fpropu(9,10,-k1+p1,mt)*
 fpropu(11,12,-k1+k2+p1,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-p4+p2,-1,p4,-4,-p2)*
 vrtx(ggg,-6,-p3,3,-k1,5,k1+p3)*
 vrtx(Uug,-2,-p1,4,k1,7,-k1+p1)*
 vrtx(Uug,10,k1-p1,6,-k1-p3,1,p4-p2)*
 vrtx(Uug,8,k1-p1,13,-k2,11,-k1+k2+p1)*
 vrtx(Uug,12,k1-k2-p1,14,k2,9,-k1+p1)
;
Local loop2diagram133=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 fpropu(7,8,-k1+p3,mt)*
 fpropu(9,10,-k1+p3,mt)*
 fpropu(11,12,-k1+k2+p3,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,-6,-p3,7,-k1+p3)*
 vrtx(Uug,10,k1-p3,2,-p1-p2,5,-k1+p4)*
 vrtx(Uug,8,k1-p3,13,-k2,11,-k1+k2+p3)*
 vrtx(Uug,12,k1-k2-p3,14,k2,9,-k1+p3)
;
Local loop2diagram134=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 fpropu(7,8,k1-p3,mt)*
 fpropu(9,10,k1-p3,mt)*
 fpropu(11,12,k1-k2-p3,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,8,-k1+p3,-6,-p3,3,k1)*
 vrtx(Uug,6,-k1+p4,2,-p1-p2,9,k1-p3)*
 vrtx(Uug,12,-k1+k2+p3,13,-k2,7,k1-p3)*
 vrtx(Uug,10,-k1+p3,14,k2,11,k1-k2-p3)
;
Local loop2diagram135=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1-p3,mt)*
 fpropu(7,8,-k1-p4,mt)*
 fpropu(9,10,-k1-p4,mt)*
 fpropu(11,12,-k1+k2-p4,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uug,6,k1+p3,-6,-p3,3,-k1)*
 vrtx(Uup,4,k1,-1,p4,7,-k1-p4)*
 vrtx(Uug,10,k1+p4,2,-p1-p2,5,-k1-p3)*
 vrtx(Uug,8,k1+p4,13,-k2,11,-k1+k2-p4)*
 vrtx(Uug,12,k1-k2+p4,14,k2,9,-k1-p4)
;
Local loop2diagram136=

 -(1)*
 glprop(1,2,p1+p2,0)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1+p3,mt)*
 fpropu(7,8,k1+p4,mt)*
 fpropu(9,10,k1+p4,mt)*
 fpropu(11,12,k1-k2+p4,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,p1+p2,-4,-p2)*
 vrtx(Uug,4,-k1,-6,-p3,5,k1+p3)*
 vrtx(Uup,8,-k1-p4,-1,p4,3,k1)*
 vrtx(Uug,6,-k1-p3,2,-p1-p2,9,k1+p4)*
 vrtx(Uug,12,-k1+k2-p4,13,-k2,7,k1+p4)*
 vrtx(Uug,10,-k1-p4,14,k2,11,k1-k2+p4)
;
Local loop2diagram137=

 -(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k1+p2,0)*
 glprop(9,10,k1-p2,0)*
 fpropu(11,12,-k1+k2+p2,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,9,k1-p2,5,-k1+p4)*
 vrtx(Uug,14,-k2,8,k1-p2,11,-k1+k2+p2)*
 vrtx(Uug,12,k1-k2-p2,10,-k1+p2,13,k2)
;
Local loop2diagram138=

 +(1/2)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k1+p2,0)*
 glprop(9,10,k1-p2,0)*
 glprop(11,12,-k1+k2+p2,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,9,k1-p2,5,-k1+p4)*
 vrtx(ggg,8,k1-p2,11,-k1+k2+p2,13,-k2)*
 vrtx(ggg,10,-k1+p2,12,k1-k2-p2,14,k2)
;
Local loop2diagram139=

 -(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,-k1,mt)*
 fpropu(5,6,-k1+p4,mt)*
 glprop(7,8,-k1+p2,0)*
 glprop(9,10,k1-p2,0)*
 ghprop(11,12,-k1+k2+p2,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uup,6,k1-p4,-1,p4,3,-k1)*
 vrtx(Uug,4,k1,7,-k1+p2,-4,-p2)*
 vrtx(Uug,2,-p1-p3,9,k1-p2,5,-k1+p4)*
 vrtx(Ghghg,14,-k2,8,k1-p2,11,-k1+k2+p2)*
 vrtx(Ghghg,12,k1-k2-p2,10,-k1+p2,13,k2)
;
Local loop2diagram140=

 +(1)*
 fpropu(1,2,p1+p3,mt)*
 fpropu(3,4,k1,mt)*
 glprop(5,6,k1+p2,0)*
 fpropu(7,8,k1+p4,mt)*
 fpropu(9,10,k1+p4,mt)*
 fpropu(11,12,k1-k2+p4,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,-6,-p3,1,p1+p3)*
 vrtx(Uug,4,-k1,5,k1+p2,-4,-p2)*
 vrtx(Uup,8,-k1-p4,-1,p4,3,k1)*
 vrtx(Uug,2,-p1-p3,6,-k1-p2,9,k1+p4)*
 vrtx(Uug,12,-k1+k2-p4,13,-k2,7,k1+p4)*
 vrtx(Uug,10,-k1-p4,14,k2,11,k1-k2+p4)
;
Local loop2diagram141=

 -(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,-k1+p1,0)*
 glprop(9,10,k1-p1,0)*
 fpropu(11,12,-k1+k2+p1,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,6,-k1+p4,9,k1-p1,1,-p2-p3)*
 vrtx(Uug,14,-k2,8,k1-p1,11,-k1+k2+p1)*
 vrtx(Uug,12,k1-k2-p1,10,-k1+p1,13,k2)
;
Local loop2diagram142=

 +(1/2)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,-k1+p1,0)*
 glprop(9,10,k1-p1,0)*
 glprop(11,12,-k1+k2+p1,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,6,-k1+p4,9,k1-p1,1,-p2-p3)*
 vrtx(ggg,8,k1-p1,11,-k1+k2+p1,13,-k2)*
 vrtx(ggg,10,-k1+p1,12,k1-k2-p1,14,k2)
;
Local loop2diagram143=

 -(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,k1,mt)*
 fpropu(5,6,k1-p4,mt)*
 glprop(7,8,-k1+p1,0)*
 glprop(9,10,k1-p1,0)*
 ghprop(11,12,-k1+k2+p1,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uup,4,-k1,-1,p4,5,k1-p4)*
 vrtx(Uug,-2,-p1,7,-k1+p1,3,k1)*
 vrtx(Uug,6,-k1+p4,9,k1-p1,1,-p2-p3)*
 vrtx(Ghghg,14,-k2,8,k1-p1,11,-k1+k2+p1)*
 vrtx(Ghghg,12,k1-k2-p1,10,-k1+p1,13,k2)
;
Local loop2diagram144=

 +(1)*
 fpropu(1,2,-p2-p3,mt)*
 fpropu(3,4,-k1,mt)*
 glprop(5,6,k1+p1,0)*
 fpropu(7,8,-k1-p4,mt)*
 fpropu(9,10,-k1-p4,mt)*
 fpropu(11,12,-k1+k2-p4,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,2,p2+p3,-6,-p3,-4,-p2)*
 vrtx(Uug,-2,-p1,5,k1+p1,3,-k1)*
 vrtx(Uup,4,k1,-1,p4,7,-k1-p4)*
 vrtx(Uug,10,k1+p4,6,-k1-p1,1,-p2-p3)*
 vrtx(Uug,8,k1+p4,13,-k2,11,-k1+k2-p4)*
 vrtx(Uug,12,k1-k2+p4,14,k2,9,-k1-p4)
;
Local loop2diagram145=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 glprop(11,12,-k1+k2+p4,0)*
 glprop(13,14,k1-k2-p4+p3,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,11,-k1+k2+p4,13,k1-k2-p4+p3)*
 vrtx(Uug,4,-k1+p4,12,k1-k2-p4,7,k2)*
 vrtx(ggg,6,k1-p1,10,-k2-p2,14,-k1+k2+p4-p3)
;
Local loop2diagram146=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,-k2-p2,mt)*
 fpropu(11,12,k1-k2-p4,mt)*
 fpropu(13,14,k1-k2-p4+p3,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,10,k2+p2,7,-k2,-4,-p2)*
 vrtx(Uug,12,-k1+k2+p4,-6,-p3,13,k1-k2-p4+p3)*
 vrtx(Uug,4,-k1+p4,8,k2,11,k1-k2-p4)*
 vrtx(Uug,14,-k1+k2+p4-p3,6,k1-p1,9,-k2-p2)
;
Local loop2diagram147=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,-k1+k2+p4,0)*
 glprop(13,14,k1-k2-p4+p3,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(ggg,-6,-p3,11,-k1+k2+p4,13,k1-k2-p4+p3)*
 vrtx(Uug,8,k2,12,k1-k2-p4,3,-k1+p4)*
 vrtx(ggg,6,k1-p2,10,-k2-p1,14,-k1+k2+p4-p3)
;
Local loop2diagram148=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 fpropu(11,12,-k1+k2+p4,mt)*
 fpropu(13,14,-k1+k2+p4-p3,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,14,k1-k2-p4+p3,-6,-p3,11,-k1+k2+p4)*
 vrtx(Uug,12,k1-k2-p4,8,k2,3,-k1+p4)*
 vrtx(Uug,10,-k2-p1,6,k1-p2,13,-k1+k2+p4-p3)
;
Local loop2diagram149=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,-k1+k2+p4,0)*
 fpropu(13,14,-k1+k2+p4-p2,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,14,k1-k2-p4+p2,11,-k1+k2+p4,-4,-p2)*
 vrtx(Uug,8,k2,12,k1-k2-p4,3,-k1+p4)*
 vrtx(Uug,6,k1-p3,10,-k2-p1,13,-k1+k2+p4-p2)
;
Local loop2diagram150=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 fpropu(11,12,k1-k2-p4,mt)*
 glprop(13,14,k1-k2-p4+p2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,12,-k1+k2+p4,13,k1-k2-p4+p2,-4,-p2)*
 vrtx(Uug,4,-k1+p4,8,k2,11,k1-k2-p4)*
 vrtx(Uug,10,-k2-p1,14,-k1+k2+p4-p2,5,k1-p3)
;
Local loop2diagram151=

 -(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2+p4,mt)*
 fpropu(11,12,k1-k2+p1,mt)*
 fpropu(13,14,k1-k2+p1+p3,mt)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uup,10,k2-p4,-1,p4,7,-k2)*
 vrtx(Uug,12,-k1+k2-p1,-6,-p3,13,k1-k2+p1+p3)*
 vrtx(Uug,8,k2,4,-k1-p1,11,k1-k2+p1)*
 vrtx(Uug,14,-k1+k2-p1-p3,6,k1-p2,9,-k2+p4)
;
Local loop2diagram152=

 -(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 fpropu(11,12,-k1+k2-p1,mt)*
 fpropu(13,14,-k1+k2-p1-p3,mt)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(Uug,14,k1-k2+p1+p3,-6,-p3,11,-k1+k2-p1)*
 vrtx(Uug,12,k1-k2+p1,4,-k1-p1,7,k2)*
 vrtx(Uug,10,-k2+p4,6,k1-p2,13,-k1+k2-p1-p3)
;
Local loop2diagram153=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,k1+p1,mt)*
 fpropu(5,6,k1-p2,mt)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 glprop(11,12,-k1+k2-p1,0)*
 glprop(13,14,k1-k2+p1+p3,0)*
 vrtx(Uug,-2,-p1,1,-k1,3,k1+p1)*
 vrtx(Uug,6,-k1+p2,2,k1,-4,-p2)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(ggg,-6,-p3,11,-k1+k2-p1,13,k1-k2+p1+p3)*
 vrtx(Uug,4,-k1-p1,12,k1-k2+p1,7,k2)*
 vrtx(Uug,10,-k2+p4,14,-k1+k2-p1-p3,5,k1-p2)
;
Local loop2diagram154=

 +(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 fpropu(5,6,-k1+p3,mt)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2+p4,mt)*
 fpropu(11,12,k1-k2+p1,mt)*
 glprop(13,14,k1-k2+p1+p2,0)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uup,10,k2-p4,-1,p4,7,-k2)*
 vrtx(Uug,12,-k1+k2-p1,13,k1-k2+p1+p2,-4,-p2)*
 vrtx(Uug,8,k2,4,-k1-p1,11,k1-k2+p1)*
 vrtx(Uug,6,k1-p3,14,-k1+k2-p1-p2,9,-k2+p4)
;
Local loop2diagram155=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,k1+p1,mt)*
 glprop(5,6,-k1+p3,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 glprop(11,12,-k1+k2-p1,0)*
 fpropu(13,14,-k1+k2-p1-p2,mt)*
 vrtx(Uug,-2,-p1,1,-k1,3,k1+p1)*
 vrtx(ggg,-6,-p3,2,k1,5,-k1+p3)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(Uug,14,k1-k2+p1+p2,11,-k1+k2-p1,-4,-p2)*
 vrtx(Uug,4,-k1-p1,12,k1-k2+p1,7,k2)*
 vrtx(Uug,10,-k2+p4,6,k1-p3,13,-k1+k2-p1-p2)
;
Local loop2diagram156=

 +(1)*
 fpropu(1,2,k1,mt)*
 glprop(3,4,k1+p2,0)*
 fpropu(5,6,k1-p3,mt)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2-p4,mt)*
 fpropu(11,12,-k1+k2-p2,mt)*
 glprop(13,14,k1-k2+p1+p2,0)*
 vrtx(Uug,2,-k1,3,k1+p2,-4,-p2)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uup,8,-k2,-1,p4,9,k2-p4)*
 vrtx(Uug,-2,-p1,13,k1-k2+p1+p2,11,-k1+k2-p2)*
 vrtx(Uug,12,k1-k2+p2,4,-k1-p2,7,k2)*
 vrtx(Uug,10,-k2+p4,14,-k1+k2-p1-p2,5,k1-p3)
;
Local loop2diagram157=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,-k1-p2,mt)*
 glprop(5,6,-k1+p3,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2+p4,mt)*
 glprop(11,12,-k1+k2-p2,0)*
 fpropu(13,14,k1-k2+p1+p2,mt)*
 vrtx(Uug,4,k1+p2,1,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,2,k1,5,-k1+p3)*
 vrtx(Uup,10,k2-p4,-1,p4,7,-k2)*
 vrtx(Uug,-2,-p1,11,-k1+k2-p2,13,k1-k2+p1+p2)*
 vrtx(Uug,8,k2,12,k1-k2+p2,3,-k1-p2)*
 vrtx(Uug,14,-k1+k2-p1-p2,6,k1-p3,9,-k2+p4)
;
Local loop2diagram158=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 fpropu(11,12,k2-p3,mt)*
 fpropu(13,14,k1+k2-p4+p2,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,12,-k2+p3,-6,-p3,7,k2)*
 vrtx(Uug,4,-k1+p4,10,-k2-p2,13,k1+k2-p4+p2)*
 vrtx(Uug,14,-k1-k2+p4-p2,6,k1-p1,11,k2-p3)
;
Local loop2diagram159=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,-k2-p2,mt)*
 glprop(11,12,-k2+p3,0)*
 glprop(13,14,k1+k2-p4+p2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,10,k2+p2,7,-k2,-4,-p2)*
 vrtx(ggg,-6,-p3,8,k2,11,-k2+p3)*
 vrtx(Uug,4,-k1+p4,13,k1+k2-p4+p2,9,-k2-p2)*
 vrtx(ggg,6,k1-p1,12,k2-p3,14,-k1-k2+p4-p2)
;
Local loop2diagram160=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 fpropu(7,8,-k2,mt)*
 fpropu(9,10,-k2-p3,mt)*
 glprop(11,12,-k2+p2,0)*
 glprop(13,14,k1+k2-p4+p3,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,10,k2+p3,-6,-p3,7,-k2)*
 vrtx(Uug,8,k2,11,-k2+p2,-4,-p2)*
 vrtx(Uug,4,-k1+p4,13,k1+k2-p4+p3,9,-k2-p3)*
 vrtx(ggg,6,k1-p1,12,k2-p2,14,-k1-k2+p4-p3)
;
Local loop2diagram161=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,k2-p2,mt)*
 fpropu(13,14,k1+k2-p4+p3,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,12,-k2+p2,8,k2,-4,-p2)*
 vrtx(Uug,4,-k1+p4,10,-k2-p3,13,k1+k2-p4+p3)*
 vrtx(Uug,14,-k1-k2+p4-p3,6,k1-p1,11,k2-p2)
;
Local loop2diagram162=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 fpropu(11,12,-k2+p3,mt)*
 fpropu(13,14,-k1-k2+p4-p1,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,8,k2,-6,-p3,11,-k2+p3)*
 vrtx(Uug,14,k1+k2-p4+p1,10,-k2-p1,3,-k1+p4)*
 vrtx(Uug,12,k2-p3,6,k1-p2,13,-k1-k2+p4-p1)
;
Local loop2diagram163=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 glprop(11,12,-k2+p3,0)*
 glprop(13,14,k1+k2-p4+p1,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(ggg,-6,-p3,8,k2,11,-k2+p3)*
 vrtx(Uug,10,-k2-p1,13,k1+k2-p4+p1,3,-k1+p4)*
 vrtx(ggg,6,k1-p2,12,k2-p3,14,-k1-k2+p4-p1)
;
Local loop2diagram164=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,k2,mt)*
 fpropu(9,10,k2+p3,mt)*
 glprop(11,12,-k2+p1,0)*
 glprop(13,14,k1+k2-p4+p3,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,8,-k2,-6,-p3,9,k2+p3)*
 vrtx(Uug,-2,-p1,11,-k2+p1,7,k2)*
 vrtx(Uug,10,-k2-p3,13,k1+k2-p4+p3,3,-k1+p4)*
 vrtx(ggg,6,k1-p2,12,k2-p1,14,-k1-k2+p4-p3)
;
Local loop2diagram165=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,-k2,0)*
 glprop(9,10,k2+p3,0)*
 fpropu(11,12,-k2+p1,mt)*
 fpropu(13,14,-k1-k2+p4-p3,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,7,-k2,9,k2+p3)*
 vrtx(Uug,-2,-p1,8,k2,11,-k2+p1)*
 vrtx(Uug,14,k1+k2-p4+p3,10,-k2-p3,3,-k1+p4)*
 vrtx(Uug,12,k2-p1,6,k1-p2,13,-k1-k2+p4-p3)
;
Local loop2diagram166=

 -(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,-k2+p2,0)*
 fpropu(13,14,-k1-k2+p4-p1,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,8,k2,11,-k2+p2,-4,-p2)*
 vrtx(Uug,14,k1+k2-p4+p1,10,-k2-p1,3,-k1+p4)*
 vrtx(Uug,6,k1-p3,12,k2-p2,13,-k1-k2+p4-p1)
;
Local loop2diagram167=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 fpropu(11,12,k2-p2,mt)*
 glprop(13,14,k1+k2-p4+p1,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,12,-k2+p2,8,k2,-4,-p2)*
 vrtx(Uug,10,-k2-p1,13,k1+k2-p4+p1,3,-k1+p4)*
 vrtx(Uug,6,k1-p3,14,-k1-k2+p4-p1,11,k2-p2)
;
Local loop2diagram168=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,-k2+p2,0)*
 fpropu(13,14,k1+k2-p4+p1,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,8,k2,11,-k2+p2,-4,-p2)*
 vrtx(Uug,4,-k1+p4,10,-k2-p1,13,k1+k2-p4+p1)*
 vrtx(Uug,14,-k1-k2+p4-p1,12,k2-p2,5,k1-p3)
;
Local loop2diagram169=

 -(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 glprop(11,12,-k2+p1,0)*
 fpropu(13,14,-k1-k2+p4-p2,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,11,-k2+p1,7,k2)*
 vrtx(Uug,14,k1+k2-p4+p2,10,-k2-p2,3,-k1+p4)*
 vrtx(Uug,6,k1-p3,12,k2-p1,13,-k1-k2+p4-p2)
;
Local loop2diagram170=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 glprop(11,12,-k2+p1,0)*
 fpropu(13,14,k1+k2-p4+p2,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,11,-k2+p1,7,k2)*
 vrtx(Uug,4,-k1+p4,10,-k2-p2,13,k1+k2-p4+p2)*
 vrtx(Uug,14,-k1-k2+p4-p2,12,k2-p1,5,k1-p3)
;
Local loop2diagram171=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,-k2-p2,mt)*
 fpropu(11,12,-k2+p1,mt)*
 glprop(13,14,k1+k2-p4+p2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,10,k2+p2,7,-k2,-4,-p2)*
 vrtx(Uug,-2,-p1,8,k2,11,-k2+p1)*
 vrtx(Uug,4,-k1+p4,13,k1+k2-p4+p2,9,-k2-p2)*
 vrtx(Uug,12,k2-p1,14,-k1-k2+p4-p2,5,k1-p3)
;
Local loop2diagram172=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 fpropu(7,8,k2,mt)*
 glprop(9,10,k2+p2,0)*
 fpropu(11,12,k2-p3,mt)*
 fpropu(13,14,-p4+p1,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,8,-k2,9,k2+p2,-4,-p2)*
 vrtx(Uug,12,-k2+p3,-6,-p3,7,k2)*
 vrtx(Uug,4,-k1+p4,6,k1-p1,13,-p4+p1)*
 vrtx(Uug,14,p4-p1,10,-k2-p2,11,k2-p3)
;
Local loop2diagram173=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,-k2-p2,mt)*
 glprop(11,12,-k2+p3,0)*
 fpropu(13,14,-p4+p1,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,10,k2+p2,7,-k2,-4,-p2)*
 vrtx(ggg,-6,-p3,8,k2,11,-k2+p3)*
 vrtx(Uug,4,-k1+p4,6,k1-p1,13,-p4+p1)*
 vrtx(Uug,14,p4-p1,12,k2-p3,9,-k2-p2)
;
Local loop2diagram174=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 fpropu(11,12,-k2+p3,mt)*
 fpropu(13,14,p4-p2,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,8,k2,-6,-p3,11,-k2+p3)*
 vrtx(Uug,14,-p4+p2,6,k1-p2,3,-k1+p4)*
 vrtx(Uug,12,k2-p3,10,-k2-p1,13,p4-p2)
;
Local loop2diagram175=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 glprop(11,12,-k2+p3,0)*
 fpropu(13,14,p4-p2,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(ggg,-6,-p3,8,k2,11,-k2+p3)*
 vrtx(Uug,14,-p4+p2,6,k1-p2,3,-k1+p4)*
 vrtx(Uug,10,-k2-p1,12,k2-p3,13,p4-p2)
;
Local loop2diagram176=

 -(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,-k2+p2,0)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,8,k2,11,-k2+p2,-4,-p2)*
 vrtx(Uug,6,k1-p3,13,-p4+p3,3,-k1+p4)*
 vrtx(ggg,14,p4-p3,10,-k2-p1,12,k2-p2)
;
Local loop2diagram177=

 -(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 fpropu(11,12,k2-p2,mt)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,12,-k2+p2,8,k2,-4,-p2)*
 vrtx(Uug,6,k1-p3,13,-p4+p3,3,-k1+p4)*
 vrtx(Uug,10,-k2-p1,14,p4-p3,11,k2-p2)
;
Local loop2diagram178=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 fpropu(7,8,-k2,mt)*
 glprop(9,10,k2+p1,0)*
 glprop(11,12,-k2+p2,0)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,-2,-p1,9,k2+p1,7,-k2)*
 vrtx(Uug,8,k2,11,-k2+p2,-4,-p2)*
 vrtx(Uug,4,-k1+p4,13,-p4+p3,5,k1-p3)*
 vrtx(ggg,14,p4-p3,10,-k2-p1,12,k2-p2)
;
Local loop2diagram179=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 glprop(7,8,-k2,0)*
 fpropu(9,10,k2+p1,mt)*
 fpropu(11,12,k2-p2,mt)*
 glprop(13,14,-p4+p3,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,-2,-p1,7,-k2,9,k2+p1)*
 vrtx(Uug,12,-k2+p2,8,k2,-4,-p2)*
 vrtx(Uug,4,-k1+p4,13,-p4+p3,5,k1-p3)*
 vrtx(Uug,10,-k2-p1,14,p4-p3,11,k2-p2)
;
Local loop2diagram180=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 fpropu(9,10,-k2,mt)*
 fpropu(11,12,-k2-p3,mt)*
 fpropu(13,14,-k1-k2+p1,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(Uug,12,k2+p3,-6,-p3,9,-k2)*
 vrtx(Uug,10,k2,6,k1-p1,13,-k1-k2+p1)*
 vrtx(Uug,14,k1+k2-p1,8,-k1+p4-p2,11,-k2-p3)
;
Local loop2diagram181=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 fpropu(9,10,k2,mt)*
 fpropu(11,12,k2+p3,mt)*
 fpropu(13,14,k1+k2-p1,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(Uug,10,-k2,-6,-p3,11,k2+p3)*
 vrtx(Uug,14,-k1-k2+p1,6,k1-p1,9,k2)*
 vrtx(Uug,12,-k2-p3,8,-k1+p4-p2,13,k1+k2-p1)
;
Local loop2diagram182=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k2,0)*
 glprop(11,12,k2+p3,0)*
 glprop(13,14,-k1-k2+p1,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,9,-k2,11,k2+p3)*
 vrtx(ggg,6,k1-p1,10,k2,13,-k1-k2+p1)*
 vrtx(ggg,8,-k1+p4-p2,12,-k2-p3,14,k1+k2-p1)
;
Local loop2diagram183=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 ghprop(9,10,-k2,0)*
 ghprop(11,12,-k2-p3,0)*
 ghprop(13,14,-k1-k2+p1,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(Ghghg,12,k2+p3,-6,-p3,9,-k2)*
 vrtx(Ghghg,10,k2,6,k1-p1,13,-k1-k2+p1)*
 vrtx(Ghghg,14,k1+k2-p1,8,-k1+p4-p2,11,-k2-p3)
;
Local loop2diagram184=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 ghprop(9,10,k2,0)*
 ghprop(11,12,k2+p3,0)*
 ghprop(13,14,k1+k2-p1,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(Ghghg,10,-k2,-6,-p3,11,k2+p3)*
 vrtx(Ghghg,14,-k1-k2+p1,6,k1-p1,9,k2)*
 vrtx(Ghghg,12,-k2-p3,8,-k1+p4-p2,13,k1+k2-p1)
;
Local loop2diagram185=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 fpropu(7,8,k1-p4+p3,mt)*
 fpropu(9,10,k2,mt)*
 glprop(11,12,k2+p2,0)*
 fpropu(13,14,k1+k2-p1,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,-6,-p3,7,k1-p4+p3)*
 vrtx(Uug,10,-k2,11,k2+p2,-4,-p2)*
 vrtx(Uug,14,-k1-k2+p1,6,k1-p1,9,k2)*
 vrtx(Uug,8,-k1+p4-p3,12,-k2-p2,13,k1+k2-p1)
;
Local loop2diagram186=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 fpropu(7,8,k1-p4+p3,mt)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,-k2-p2,mt)*
 glprop(13,14,-k1-k2+p1,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,-6,-p3,7,k1-p4+p3)*
 vrtx(Uug,12,k2+p2,9,-k2,-4,-p2)*
 vrtx(ggg,6,k1-p1,10,k2,13,-k1-k2+p1)*
 vrtx(Uug,8,-k1+p4-p3,14,k1+k2-p1,11,-k2-p2)
;
Local loop2diagram187=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,-k1+p4-p3,mt)*
 fpropu(9,10,-k2,mt)*
 glprop(11,12,k2+p1,0)*
 fpropu(13,14,-k1-k2+p2,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,8,k1-p4+p3,-6,-p3,3,-k1+p4)*
 vrtx(Uug,-2,-p1,11,k2+p1,9,-k2)*
 vrtx(Uug,10,k2,6,k1-p2,13,-k1-k2+p2)*
 vrtx(Uug,14,k1+k2-p2,12,-k2-p1,7,-k1+p4-p3)
;
Local loop2diagram188=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,-k1+p4-p3,mt)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,k2+p1,mt)*
 glprop(13,14,-k1-k2+p2,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,8,k1-p4+p3,-6,-p3,3,-k1+p4)*
 vrtx(Uug,-2,-p1,9,-k2,11,k2+p1)*
 vrtx(ggg,6,k1-p2,10,k2,13,-k1-k2+p2)*
 vrtx(Uug,12,-k2-p1,14,k1+k2-p2,7,-k1+p4-p3)
;
Local loop2diagram189=

 +(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 fpropu(5,6,-k1-p4,mt)*
 fpropu(7,8,-k1-p1-p2,mt)*
 fpropu(9,10,k2,mt)*
 fpropu(11,12,k2+p3,mt)*
 glprop(13,14,-k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uup,2,k1,-1,p4,5,-k1-p4)*
 vrtx(Uug,8,k1+p1+p2,4,-k1-p1,-4,-p2)*
 vrtx(Uug,10,-k2,-6,-p3,11,k2+p3)*
 vrtx(Uug,6,k1+p4,13,-k1-k2-p4,9,k2)*
 vrtx(Uug,12,-k2-p3,14,k1+k2+p4,7,-k1-p1-p2)
;
Local loop2diagram190=

 +(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 fpropu(5,6,-k1-p4,mt)*
 fpropu(7,8,-k1-p1-p2,mt)*
 glprop(9,10,-k2,0)*
 glprop(11,12,k2+p3,0)*
 fpropu(13,14,-k1-k2-p4,mt)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uup,2,k1,-1,p4,5,-k1-p4)*
 vrtx(Uug,8,k1+p1+p2,4,-k1-p1,-4,-p2)*
 vrtx(ggg,-6,-p3,9,-k2,11,k2+p3)*
 vrtx(Uug,6,k1+p4,10,k2,13,-k1-k2-p4)*
 vrtx(Uug,14,k1+k2+p4,12,-k2-p3,7,-k1-p1-p2)
;
Local loop2diagram191=

 +(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 fpropu(5,6,-k1-p4,mt)*
 glprop(7,8,k1+p1+p3,0)*
 fpropu(9,10,k2,mt)*
 glprop(11,12,k2+p2,0)*
 glprop(13,14,-k1-k2-p4,0)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uup,2,k1,-1,p4,5,-k1-p4)*
 vrtx(ggg,-6,-p3,4,-k1-p1,7,k1+p1+p3)*
 vrtx(Uug,10,-k2,11,k2+p2,-4,-p2)*
 vrtx(Uug,6,k1+p4,13,-k1-k2-p4,9,k2)*
 vrtx(ggg,8,-k1-p1-p3,12,-k2-p2,14,k1+k2+p4)
;
Local loop2diagram192=

 +(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 fpropu(5,6,-k1-p4,mt)*
 glprop(7,8,k1+p1+p3,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,-k2-p2,mt)*
 fpropu(13,14,-k1-k2-p4,mt)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uup,2,k1,-1,p4,5,-k1-p4)*
 vrtx(ggg,-6,-p3,4,-k1-p1,7,k1+p1+p3)*
 vrtx(Uug,12,k2+p2,9,-k2,-4,-p2)*
 vrtx(Uug,6,k1+p4,10,k2,13,-k1-k2-p4)*
 vrtx(Uug,14,k1+k2+p4,8,-k1-p1-p3,11,-k2-p2)
;
Local loop2diagram193=

 -(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,k1+p1+p3,0)*
 fpropu(9,10,-k2,mt)*
 fpropu(11,12,-k2+p4,mt)*
 fpropu(13,14,-k1-k2+p2,mt)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,4,-k1-p1,7,k1+p1+p3)*
 vrtx(Uup,12,k2-p4,-1,p4,9,-k2)*
 vrtx(Uug,10,k2,6,k1-p2,13,-k1-k2+p2)*
 vrtx(Uug,14,k1+k2-p2,8,-k1-p1-p3,11,-k2+p4)
;
Local loop2diagram194=

 -(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,k1+p1+p3,0)*
 fpropu(9,10,k2,mt)*
 fpropu(11,12,k2-p4,mt)*
 fpropu(13,14,k1+k2-p2,mt)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,4,-k1-p1,7,k1+p1+p3)*
 vrtx(Uup,10,-k2,-1,p4,11,k2-p4)*
 vrtx(Uug,14,-k1-k2+p2,6,k1-p2,9,k2)*
 vrtx(Uug,12,-k2+p4,8,-k1-p1-p3,13,k1+k2-p2)
;
Local loop2diagram195=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,k1+p1,mt)*
 fpropu(5,6,k1-p2,mt)*
 fpropu(7,8,k1+p1+p3,mt)*
 fpropu(9,10,-k2,mt)*
 fpropu(11,12,-k2+p4,mt)*
 glprop(13,14,-k1-k2+p2,0)*
 vrtx(Uug,-2,-p1,1,-k1,3,k1+p1)*
 vrtx(Uug,6,-k1+p2,2,k1,-4,-p2)*
 vrtx(Uug,4,-k1-p1,-6,-p3,7,k1+p1+p3)*
 vrtx(Uup,12,k2-p4,-1,p4,9,-k2)*
 vrtx(Uug,10,k2,13,-k1-k2+p2,5,k1-p2)*
 vrtx(Uug,8,-k1-p1-p3,14,k1+k2-p2,11,-k2+p4)
;
Local loop2diagram196=

 +(1)*
 fpropu(1,2,k1,mt)*
 glprop(3,4,k1+p2,0)*
 fpropu(5,6,k1+p4,mt)*
 fpropu(7,8,k1+p1+p2,mt)*
 fpropu(9,10,-k2,mt)*
 fpropu(11,12,-k2-p3,mt)*
 glprop(13,14,-k1-k2-p4,0)*
 vrtx(Uug,2,-k1,3,k1+p2,-4,-p2)*
 vrtx(Uup,6,-k1-p4,-1,p4,1,k1)*
 vrtx(Uug,-2,-p1,4,-k1-p2,7,k1+p1+p2)*
 vrtx(Uug,12,k2+p3,-6,-p3,9,-k2)*
 vrtx(Uug,10,k2,13,-k1-k2-p4,5,k1+p4)*
 vrtx(Uug,8,-k1-p1-p2,14,k1+k2+p4,11,-k2-p3)
;
Local loop2diagram197=

 +(1)*
 fpropu(1,2,k1,mt)*
 glprop(3,4,k1+p2,0)*
 fpropu(5,6,k1+p4,mt)*
 fpropu(7,8,k1+p1+p2,mt)*
 glprop(9,10,-k2,0)*
 glprop(11,12,k2+p3,0)*
 fpropu(13,14,k1+k2+p4,mt)*
 vrtx(Uug,2,-k1,3,k1+p2,-4,-p2)*
 vrtx(Uup,6,-k1-p4,-1,p4,1,k1)*
 vrtx(Uug,-2,-p1,4,-k1-p2,7,k1+p1+p2)*
 vrtx(ggg,-6,-p3,9,-k2,11,k2+p3)*
 vrtx(Uug,14,-k1-k2-p4,10,k2,5,k1+p4)*
 vrtx(Uug,8,-k1-p1-p2,12,-k2-p3,13,k1+k2+p4)
;
Local loop2diagram198=

 +(1)*
 fpropu(1,2,k1,mt)*
 glprop(3,4,k1+p2,0)*
 fpropu(5,6,k1+p4,mt)*
 glprop(7,8,k1+p2+p3,0)*
 fpropu(9,10,-k2,mt)*
 glprop(11,12,k2+p1,0)*
 glprop(13,14,-k1-k2-p4,0)*
 vrtx(Uug,2,-k1,3,k1+p2,-4,-p2)*
 vrtx(Uup,6,-k1-p4,-1,p4,1,k1)*
 vrtx(ggg,-6,-p3,4,-k1-p2,7,k1+p2+p3)*
 vrtx(Uug,-2,-p1,11,k2+p1,9,-k2)*
 vrtx(Uug,10,k2,13,-k1-k2-p4,5,k1+p4)*
 vrtx(ggg,8,-k1-p2-p3,12,-k2-p1,14,k1+k2+p4)
;
Local loop2diagram199=

 +(1)*
 fpropu(1,2,k1,mt)*
 glprop(3,4,k1+p2,0)*
 fpropu(5,6,k1+p4,mt)*
 glprop(7,8,k1+p2+p3,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,k2+p1,mt)*
 fpropu(13,14,k1+k2+p4,mt)*
 vrtx(Uug,2,-k1,3,k1+p2,-4,-p2)*
 vrtx(Uup,6,-k1-p4,-1,p4,1,k1)*
 vrtx(ggg,-6,-p3,4,-k1-p2,7,k1+p2+p3)*
 vrtx(Uug,-2,-p1,9,-k2,11,k2+p1)*
 vrtx(Uug,14,-k1-k2-p4,10,k2,5,k1+p4)*
 vrtx(Uug,12,-k2-p1,8,-k1-p2-p3,13,k1+k2+p4)
;
Local loop2diagram200=

 -(1)*
 fpropu(1,2,k1,mt)*
 glprop(3,4,k1+p2,0)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1+p2+p3,0)*
 fpropu(9,10,-k2,mt)*
 fpropu(11,12,-k2+p4,mt)*
 fpropu(13,14,-k1-k2+p1,mt)*
 vrtx(Uug,2,-k1,3,k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(ggg,-6,-p3,4,-k1-p2,7,k1+p2+p3)*
 vrtx(Uup,12,k2-p4,-1,p4,9,-k2)*
 vrtx(Uug,10,k2,6,k1-p1,13,-k1-k2+p1)*
 vrtx(Uug,14,k1+k2-p1,8,-k1-p2-p3,11,-k2+p4)
;
Local loop2diagram201=

 -(1)*
 fpropu(1,2,k1,mt)*
 glprop(3,4,k1+p2,0)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1+p2+p3,0)*
 fpropu(9,10,k2,mt)*
 fpropu(11,12,k2-p4,mt)*
 fpropu(13,14,k1+k2-p1,mt)*
 vrtx(Uug,2,-k1,3,k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(ggg,-6,-p3,4,-k1-p2,7,k1+p2+p3)*
 vrtx(Uup,10,-k2,-1,p4,11,k2-p4)*
 vrtx(Uug,14,-k1-k2+p1,6,k1-p1,9,k2)*
 vrtx(Uug,12,-k2+p4,8,-k1-p2-p3,13,k1+k2-p1)
;
Local loop2diagram202=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,-k1-p2,mt)*
 fpropu(5,6,-k1+p1,mt)*
 fpropu(7,8,-k1-p2-p3,mt)*
 fpropu(9,10,k2,mt)*
 fpropu(11,12,k2-p4,mt)*
 glprop(13,14,-k1-k2+p1,0)*
 vrtx(Uug,4,k1+p2,1,-k1,-4,-p2)*
 vrtx(Uug,-2,-p1,2,k1,5,-k1+p1)*
 vrtx(Uug,8,k1+p2+p3,-6,-p3,3,-k1-p2)*
 vrtx(Uup,10,-k2,-1,p4,11,k2-p4)*
 vrtx(Uug,6,k1-p1,13,-k1-k2+p1,9,k2)*
 vrtx(Uug,12,-k2+p4,14,k1+k2-p1,7,-k1-p2-p3)
;
Local loop2diagram203=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1-p3,mt)*
 fpropu(5,6,-k1-p4,mt)*
 glprop(7,8,k1+p1+p3,0)*
 fpropu(9,10,k2,mt)*
 glprop(11,12,k2+p2,0)*
 glprop(13,14,-k1-k2-p4,0)*
 vrtx(Uug,4,k1+p3,-6,-p3,1,-k1)*
 vrtx(Uup,2,k1,-1,p4,5,-k1-p4)*
 vrtx(Uug,-2,-p1,7,k1+p1+p3,3,-k1-p3)*
 vrtx(Uug,10,-k2,11,k2+p2,-4,-p2)*
 vrtx(Uug,6,k1+p4,13,-k1-k2-p4,9,k2)*
 vrtx(ggg,8,-k1-p1-p3,12,-k2-p2,14,k1+k2+p4)
;
Local loop2diagram204=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1-p3,mt)*
 fpropu(5,6,-k1-p4,mt)*
 glprop(7,8,k1+p1+p3,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,-k2-p2,mt)*
 fpropu(13,14,-k1-k2-p4,mt)*
 vrtx(Uug,4,k1+p3,-6,-p3,1,-k1)*
 vrtx(Uup,2,k1,-1,p4,5,-k1-p4)*
 vrtx(Uug,-2,-p1,7,k1+p1+p3,3,-k1-p3)*
 vrtx(Uug,12,k2+p2,9,-k2,-4,-p2)*
 vrtx(Uug,6,k1+p4,10,k2,13,-k1-k2-p4)*
 vrtx(Uug,14,k1+k2+p4,8,-k1-p1-p3,11,-k2-p2)
;
Local loop2diagram205=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1+p3,mt)*
 fpropu(5,6,k1+p4,mt)*
 glprop(7,8,k1+p2+p3,0)*
 fpropu(9,10,-k2,mt)*
 glprop(11,12,k2+p1,0)*
 glprop(13,14,-k1-k2-p4,0)*
 vrtx(Uug,2,-k1,-6,-p3,3,k1+p3)*
 vrtx(Uup,6,-k1-p4,-1,p4,1,k1)*
 vrtx(Uug,4,-k1-p3,7,k1+p2+p3,-4,-p2)*
 vrtx(Uug,-2,-p1,11,k2+p1,9,-k2)*
 vrtx(Uug,10,k2,13,-k1-k2-p4,5,k1+p4)*
 vrtx(ggg,8,-k1-p2-p3,12,-k2-p1,14,k1+k2+p4)
;
Local loop2diagram206=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1+p3,mt)*
 fpropu(5,6,k1+p4,mt)*
 glprop(7,8,k1+p2+p3,0)*
 glprop(9,10,-k2,0)*
 fpropu(11,12,k2+p1,mt)*
 fpropu(13,14,k1+k2+p4,mt)*
 vrtx(Uug,2,-k1,-6,-p3,3,k1+p3)*
 vrtx(Uup,6,-k1-p4,-1,p4,1,k1)*
 vrtx(Uug,4,-k1-p3,7,k1+p2+p3,-4,-p2)*
 vrtx(Uug,-2,-p1,9,-k2,11,k2+p1)*
 vrtx(Uug,14,-k1-k2-p4,10,k2,5,k1+p4)*
 vrtx(Uug,12,-k2-p1,8,-k1-p2-p3,13,k1+k2+p4)
;
Local loop2diagram207=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1+p3,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1+p2+p3,0)*
 fpropu(9,10,-k2,mt)*
 fpropu(11,12,-k2+p4,mt)*
 fpropu(13,14,-k1-k2+p1,mt)*
 vrtx(Uug,2,-k1,-6,-p3,3,k1+p3)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1-p3,7,k1+p2+p3,-4,-p2)*
 vrtx(Uup,12,k2-p4,-1,p4,9,-k2)*
 vrtx(Uug,10,k2,6,k1-p1,13,-k1-k2+p1)*
 vrtx(Uug,14,k1+k2-p1,8,-k1-p2-p3,11,-k2+p4)
;
Local loop2diagram208=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1+p3,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1+p2+p3,0)*
 fpropu(9,10,k2,mt)*
 fpropu(11,12,k2-p4,mt)*
 fpropu(13,14,k1+k2-p1,mt)*
 vrtx(Uug,2,-k1,-6,-p3,3,k1+p3)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1-p3,7,k1+p2+p3,-4,-p2)*
 vrtx(Uup,10,-k2,-1,p4,11,k2-p4)*
 vrtx(Uug,14,-k1-k2+p1,6,k1-p1,9,k2)*
 vrtx(Uug,12,-k2+p4,8,-k1-p2-p3,13,k1+k2-p1)
;
Local loop2diagram209=

 +(1)*
 glprop(1,2,-k1,0)*
 glprop(3,4,k1+p3,0)*
 fpropu(5,6,-k1+p1,mt)*
 fpropu(7,8,-k1-p2-p3,mt)*
 fpropu(9,10,k2,mt)*
 fpropu(11,12,k2-p4,mt)*
 glprop(13,14,-k1-k2+p1,0)*
 vrtx(ggg,-6,-p3,1,-k1,3,k1+p3)*
 vrtx(Uug,-2,-p1,2,k1,5,-k1+p1)*
 vrtx(Uug,8,k1+p2+p3,4,-k1-p3,-4,-p2)*
 vrtx(Uup,10,-k2,-1,p4,11,k2-p4)*
 vrtx(Uug,6,k1-p1,13,-k1-k2+p1,9,k2)*
 vrtx(Uug,12,-k2+p4,14,k1+k2-p1,7,-k1-p2-p3)
;
Local loop2diagram210=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 fpropu(11,12,k1+k2-p4+p2,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,6,k1-p1,9,-k1+p1+p3)*
 vrtx(Uug,14,-k2,8,-k1+p4-p2,11,k1+k2-p4+p2)*
 vrtx(Uug,12,-k1-k2+p4-p2,10,k1-p1-p3,13,k2)
;
Local loop2diagram211=

 +(1/2)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 glprop(11,12,k1+k2-p4+p2,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,6,k1-p1,9,-k1+p1+p3)*
 vrtx(ggg,8,-k1+p4-p2,11,k1+k2-p4+p2,13,-k2)*
 vrtx(ggg,10,k1-p1-p3,12,-k1-k2+p4-p2,14,k2)
;
Local loop2diagram212=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 ghprop(11,12,k1+k2-p4+p2,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(ggg,-6,-p3,6,k1-p1,9,-k1+p1+p3)*
 vrtx(Ghghg,14,-k2,8,-k1+p4-p2,11,k1+k2-p4+p2)*
 vrtx(Ghghg,12,-k1-k2+p4-p2,10,k1-p1-p3,13,k2)
;
Local loop2diagram213=

 +(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 glprop(5,6,-k1+p1,0)*
 fpropu(7,8,k1-p4+p3,mt)*
 fpropu(9,10,k1-p1-p2,mt)*
 fpropu(11,12,k1+k2-p4+p3,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,-2,-p1,5,-k1+p1,1,k1)*
 vrtx(Uug,4,-k1+p4,-6,-p3,7,k1-p4+p3)*
 vrtx(Uug,10,-k1+p1+p2,6,k1-p1,-4,-p2)*
 vrtx(Uug,8,-k1+p4-p3,13,-k2,11,k1+k2-p4+p3)*
 vrtx(Uug,12,-k1-k2+p4-p3,14,k2,9,k1-p1-p2)
;
Local loop2diagram214=

 -(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 fpropu(11,12,k1+k2-p4+p1,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,7,k1-p4+p1,3,-k1+p4)*
 vrtx(ggg,-6,-p3,6,k1-p2,9,-k1+p2+p3)*
 vrtx(Uug,14,-k2,8,-k1+p4-p1,11,k1+k2-p4+p1)*
 vrtx(Uug,12,-k1-k2+p4-p1,10,k1-p2-p3,13,k2)
;
Local loop2diagram215=

 +(1/2)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 glprop(11,12,k1+k2-p4+p1,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,7,k1-p4+p1,3,-k1+p4)*
 vrtx(ggg,-6,-p3,6,k1-p2,9,-k1+p2+p3)*
 vrtx(ggg,8,-k1+p4-p1,11,k1+k2-p4+p1,13,-k2)*
 vrtx(ggg,10,k1-p2-p3,12,-k1-k2+p4-p1,14,k2)
;
Local loop2diagram216=

 -(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 ghprop(11,12,k1+k2-p4+p1,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,7,k1-p4+p1,3,-k1+p4)*
 vrtx(ggg,-6,-p3,6,k1-p2,9,-k1+p2+p3)*
 vrtx(Ghghg,14,-k2,8,-k1+p4-p1,11,k1+k2-p4+p1)*
 vrtx(Ghghg,12,-k1-k2+p4-p1,10,k1-p2-p3,13,k2)
;
Local loop2diagram217=

 +(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 glprop(5,6,-k1+p2,0)*
 fpropu(7,8,-k1+p4-p3,mt)*
 fpropu(9,10,-k1+p1+p2,mt)*
 fpropu(11,12,-k1-k2+p4-p3,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,5,-k1+p2,-4,-p2)*
 vrtx(Uug,8,k1-p4+p3,-6,-p3,3,-k1+p4)*
 vrtx(Uug,-2,-p1,6,k1-p2,9,-k1+p1+p2)*
 vrtx(Uug,12,k1+k2-p4+p3,13,-k2,7,-k1+p4-p3)*
 vrtx(Uug,10,k1-p1-p2,14,k2,11,-k1-k2+p4-p3)
;
Local loop2diagram218=

 -(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 fpropu(11,12,k1+k2-p4+p1,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,-2,-p1,7,k1-p4+p1,3,-k1+p4)*
 vrtx(Uug,6,k1-p3,9,-k1+p2+p3,-4,-p2)*
 vrtx(Uug,14,-k2,8,-k1+p4-p1,11,k1+k2-p4+p1)*
 vrtx(Uug,12,-k1-k2+p4-p1,10,k1-p2-p3,13,k2)
;
Local loop2diagram219=

 +(1/2)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 glprop(11,12,k1+k2-p4+p1,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,-2,-p1,7,k1-p4+p1,3,-k1+p4)*
 vrtx(Uug,6,k1-p3,9,-k1+p2+p3,-4,-p2)*
 vrtx(ggg,8,-k1+p4-p1,11,k1+k2-p4+p1,13,-k2)*
 vrtx(ggg,10,k1-p2-p3,12,-k1-k2+p4-p1,14,k2)
;
Local loop2diagram220=

 -(1)*
 fpropu(1,2,-k1,mt)*
 fpropu(3,4,-k1+p4,mt)*
 fpropu(5,6,-k1+p3,mt)*
 glprop(7,8,k1-p4+p1,0)*
 glprop(9,10,-k1+p2+p3,0)*
 ghprop(11,12,k1+k2-p4+p1,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,4,k1-p4,-1,p4,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,-2,-p1,7,k1-p4+p1,3,-k1+p4)*
 vrtx(Uug,6,k1-p3,9,-k1+p2+p3,-4,-p2)*
 vrtx(Ghghg,14,-k2,8,-k1+p4-p1,11,k1+k2-p4+p1)*
 vrtx(Ghghg,12,-k1-k2+p4-p1,10,k1-p2-p3,13,k2)
;
Local loop2diagram221=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 fpropu(11,12,k1+k2-p4+p2,mt)*
 fpropu(13,14,k2,mt)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,9,-k1+p1+p3,5,k1-p3)*
 vrtx(Uug,14,-k2,8,-k1+p4-p2,11,k1+k2-p4+p2)*
 vrtx(Uug,12,-k1-k2+p4-p2,10,k1-p1-p3,13,k2)
;
Local loop2diagram222=

 +(1/2)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 glprop(11,12,k1+k2-p4+p2,0)*
 glprop(13,14,-k2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,9,-k1+p1+p3,5,k1-p3)*
 vrtx(ggg,8,-k1+p4-p2,11,k1+k2-p4+p2,13,-k2)*
 vrtx(ggg,10,k1-p1-p3,12,-k1-k2+p4-p2,14,k2)
;
Local loop2diagram223=

 -(1)*
 fpropu(1,2,k1,mt)*
 fpropu(3,4,k1-p4,mt)*
 fpropu(5,6,k1-p3,mt)*
 glprop(7,8,k1-p4+p2,0)*
 glprop(9,10,-k1+p1+p3,0)*
 ghprop(11,12,k1+k2-p4+p2,0)*
 ghprop(13,14,k2,0)*
 vrtx(Uup,2,-k1,-1,p4,3,k1-p4)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,4,-k1+p4,7,k1-p4+p2,-4,-p2)*
 vrtx(Uug,-2,-p1,9,-k1+p1+p3,5,k1-p3)*
 vrtx(Ghghg,14,-k2,8,-k1+p4-p2,11,k1+k2-p4+p2)*
 vrtx(Ghghg,12,-k1-k2+p4-p2,10,k1-p1-p3,13,k2)
;
Local loop2diagram224=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,k1+p1,mt)*
 fpropu(5,6,k1-p2,mt)*
 fpropu(7,8,k1-p4+p1,mt)*
 fpropu(9,10,k1-p2-p3,mt)*
 fpropu(11,12,k1+k2-p4+p1,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,-k1,3,k1+p1)*
 vrtx(Uug,6,-k1+p2,2,k1,-4,-p2)*
 vrtx(Uup,4,-k1-p1,-1,p4,7,k1-p4+p1)*
 vrtx(Uug,10,-k1+p2+p3,-6,-p3,5,k1-p2)*
 vrtx(Uug,8,-k1+p4-p1,13,-k2,11,k1+k2-p4+p1)*
 vrtx(Uug,12,-k1-k2+p4-p1,14,k2,9,k1-p2-p3)
;
Local loop2diagram225=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,k1+p1,mt)*
 fpropu(5,6,k1-p2,mt)*
 fpropu(7,8,k1+p1+p3,mt)*
 fpropu(9,10,k1+p4-p2,mt)*
 fpropu(11,12,k1+k2+p1+p3,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,-k1,3,k1+p1)*
 vrtx(Uug,6,-k1+p2,2,k1,-4,-p2)*
 vrtx(Uug,4,-k1-p1,-6,-p3,7,k1+p1+p3)*
 vrtx(Uup,10,-k1-p4+p2,-1,p4,5,k1-p2)*
 vrtx(Uug,8,-k1-p1-p3,13,-k2,11,k1+k2+p1+p3)*
 vrtx(Uug,12,-k1-k2-p1-p3,14,k2,9,k1+p4-p2)
;
Local loop2diagram226=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,k1+p1,mt)*
 glprop(5,6,-k1+p3,0)*
 fpropu(7,8,k1-p4+p1,mt)*
 fpropu(9,10,k1-p2-p3,mt)*
 fpropu(11,12,k1+k2-p4+p1,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,1,-k1,3,k1+p1)*
 vrtx(ggg,-6,-p3,2,k1,5,-k1+p3)*
 vrtx(Uup,4,-k1-p1,-1,p4,7,k1-p4+p1)*
 vrtx(Uug,10,-k1+p2+p3,6,k1-p3,-4,-p2)*
 vrtx(Uug,8,-k1+p4-p1,13,-k2,11,k1+k2-p4+p1)*
 vrtx(Uug,12,-k1-k2+p4-p1,14,k2,9,k1-p2-p3)
;
Local loop2diagram227=

 +(1)*
 fpropu(1,2,-k1,mt)*
 glprop(3,4,k1+p1,0)*
 fpropu(5,6,-k1+p3,mt)*
 fpropu(7,8,-k1-p1-p2,mt)*
 fpropu(9,10,-k1-p4+p3,mt)*
 fpropu(11,12,-k1-k2-p1-p2,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,-2,-p1,3,k1+p1,1,-k1)*
 vrtx(Uug,2,k1,-6,-p3,5,-k1+p3)*
 vrtx(Uug,8,k1+p1+p2,4,-k1-p1,-4,-p2)*
 vrtx(Uup,6,k1-p3,-1,p4,9,-k1-p4+p3)*
 vrtx(Uug,12,k1+k2+p1+p2,13,-k2,7,-k1-p1-p2)*
 vrtx(Uug,10,k1+p4-p3,14,k2,11,-k1-k2-p1-p2)
;
Local loop2diagram228=

 +(1)*
 glprop(1,2,-k1,0)*
 fpropu(3,4,-k1-p2,mt)*
 glprop(5,6,-k1+p3,0)*
 fpropu(7,8,-k1+p4-p2,mt)*
 fpropu(9,10,-k1+p1+p3,mt)*
 fpropu(11,12,-k1-k2+p4-p2,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,4,k1+p2,1,-k1,-4,-p2)*
 vrtx(ggg,-6,-p3,2,k1,5,-k1+p3)*
 vrtx(Uup,8,k1-p4+p2,-1,p4,3,-k1-p2)*
 vrtx(Uug,-2,-p1,6,k1-p3,9,-k1+p1+p3)*
 vrtx(Uug,12,k1+k2-p4+p2,13,-k2,7,-k1+p4-p2)*
 vrtx(Uug,10,k1-p1-p3,14,k2,11,-k1-k2+p4-p2)
;
Local loop2diagram229=

 +(1)*
 fpropu(1,2,k1,mt)*
 glprop(3,4,k1+p2,0)*
 fpropu(5,6,k1-p3,mt)*
 fpropu(7,8,k1+p1+p2,mt)*
 fpropu(9,10,k1+p4-p3,mt)*
 fpropu(11,12,k1+k2+p1+p2,mt)*
 glprop(13,14,-k2,0)*
 vrtx(Uug,2,-k1,3,k1+p2,-4,-p2)*
 vrtx(Uug,6,-k1+p3,-6,-p3,1,k1)*
 vrtx(Uug,-2,-p1,4,-k1-p2,7,k1+p1+p2)*
 vrtx(Uup,10,-k1-p4+p3,-1,p4,5,k1-p3)*
 vrtx(Uug,8,-k1-p1-p2,13,-k2,11,k1+k2+p1+p2)*
 vrtx(Uug,12,-k1-k2-p1-p2,14,k2,9,k1+p4-p3)
;

* end

